"""
NetSuite SuiteAnalytics Connect (NS2) Schema
Auto-generated from NS 2 Schemma.xlsx
Use SQL-92 standard syntax with these tables and columns.
"""

NETSUITE_SCHEMA = """
NetSuite SuiteAnalytics Connect (NS2) Database Schema
======================================================
Use SQL-92 standard syntax. Table and column names are case-insensitive.

IMPORTANT SQL-92 RULES:
- Use standard JOINs: INNER JOIN, LEFT JOIN, RIGHT JOIN
- For row limits, wrap query: SELECT * FROM (your_query) WHERE ROWNUM <= N
- Use single quotes for strings: WHERE status = 'Active'
- Use IS NULL / IS NOT NULL for null checks
- Date format: TO_DATE('2024-01-01', 'YYYY-MM-DD')
- Boolean fields use 'T' for true and 'F' for false

TABLES AND COLUMNS:

EMPLOYEE:
  ID, HIREDATE, TITLE, LASTREVIEWDATE, NEXTREVIEWDATE, RELEASEDATE, LASTMODIFIEDDATE, LABORCOST, NAMEORIG, DATECREATED, ACCOUNTNUMBER, ADDRESSBOOK, APPROVALLIMIT, APPROVER, BIRTHDATE, CLASS, DEFAULTACCTCORPCARDEXP, DEFAULTEXPENSEREPORTCURRENCY, DEPARTMENT, EMAIL, EMPLOYEETYPE, FIRSTNAME, INITIALS, ISINACTIVE, LASTNAME, GIVEACCESS, MIDDLENAME, COMMENTS, PHONE, EXTERNALID, SALESROLE, SALUTATION, SUBSIDIARY, SUPERVISOR, ENTITYTITLE

CUSTOMER:
  ACCOUNTNUMBER, ALCOHOLRECIPIENTTYPE, ALTEMAIL, ALTPHONE, BILLINGRATECARD, BILLINGSCHEDULE, BILLINGTRANSACTIONTYPE, CATEGORY, COMMENTS, COMPANYNAME, CONSOLDAYSOVERDUE, CONSOLDEPOSITBALANCE, CONSOLBALANCE, CONSOLUNBILLEDORDERS, CONVERTEDTOCONTACT, CONVERTEDTOCUSTOMER, DATECREATED, ONCREDITHOLD, CREDITLIMIT, CURRENCY, EXTERNALID, ID, TYPE, STARTDATE, DATECLOSED, FIRSTORDERDATE, FIRSTSALEDATE, LASTMODIFIEDDATE, LASTORDERDATE, LASTSALEDATE, DAYSOVERDUE, DEFAULTORDERPRIORITY, DEPOSITBALANCE, EMAIL, FAX, FIRSTSALEPERIOD, FIRSTVISIT, FIRSTNAME, FULLNAME, HOMEPHONE, ISEXPLICITCONVERSION, ISJOB, ISPERSON, TAXABLE, EMAILPREFERENCE, ISINACTIVE, LANGUAGE, LASTSALEPERIOD, LASTVISIT, LASTNAME, LEADSOURCE, GIVEACCESS, MIDDLENAME, MOBILEPHONE, PRICELEVEL, ENTITYID, OPENINGBALANCE, PARENT, PARTNER, TERMS, PHONE, CONTACT, PRINTONCHECKAS, PROBABILITY, REFERRER, REMINDERDAYS, REPRESENTINGSUBSIDIARY, RESALENUMBER, SALESREP, TERRITORY, SALUTATION, SHIPCOMPLETE, ENTITYSTATUS, ENTITY<CUSTOMERSUBSIDIARYRELATIONSHIP.SUBSIDIARY, SUBSIDIARY, TAXITEM, THIRDPARTYACCT, THIRDPARTYCARRIER, THIRDPARTYCOUNTRY, THIRDPARTYZIPCODE, UNBILLEDORDERS, URL, VATREGNUMBER, WEBLEAD, NAMEORIG, ENTITYTITLE

VENDOR:
  LASTMODIFIEDDATE, LABORCOST, NAMEORIG, PURCHASEORDERAMOUNT, PURCHASEORDERQUANTITY, PURCHASEORDERQUANTITYDIFF, RECEIPTAMOUNT, RECEIPTQUANTITY, RECEIPTQUANTITYDIFF, DATECREATED, ENTITYTITLE, SUBSIDIARYEDITION, TAXIDNUM, ACCOUNTNUMBER, ALTEMAIL, ALTPHONE, DEFAULTBILLINGADDRESS, BILLINGCLASS, COMMENTS, COMPANYNAME, CREDITLIMIT, CURRENCY, EMAIL, EXPENSEACCOUNT, FAX, FULLNAME, HOMEPHONE, INTRANSITBALANCE, INCOTERM, ISPERSON, IS1099ELIGIBLE, ISINACTIVE, GIVEACCESS, MOBILEPHONE, FIRSTNAME, LASTNAME, MIDDLENAME, ENTITYID, BALANCE, BALANCEPRIMARY, PAYABLESACCOUNT, TERMS, PHONE, PREPAYMENTBALANCE, PRINTONCHECKAS, REPRESENTINGSUBSIDIARY, DEFAULTSHIPPINGADDRESS, BILLSTATE, SUBSIDIARY, TAXITEM, DEFAULTTAXREG, TIMEAPPROVER, UNBILLEDORDERS, UNBILLEDORDERSPRIMARY, URL, VATREGNUMBER, EXTERNALID, ID, TYPE, BILLZIP/SHIPZIP

TRANSACTION:
  POSTINGPERIOD, ACTIONITEM, BILLINGADDRESS, CLOSEDATE, ENTITYSTATUS, CURRENCY, LASTMODIFIEDDATE, EMAIL, ENDDATE, EXPECTEDCLOSEDATE, FAX, FOB, FORECASTTYPE, TAXREGOVERRIDE, LEADSOURCE, MEMO, MEMORIZED, MESSAGE, NEEDSBILL, PARTNER, TERMS, PROBABILITY, PROJECTEDTOTAL, COUPONCODE, OTHERREFNUM, REVERSAL, EMPLOYEE, SHIPPINGADDRESS, PICKEDUPDATE, SHIPMETHOD, STARTDATE, STATUS, TITLE, TRANDATE, TRANID, ID, SOURCE, TYPE, WEIGHTEDTOTAL, WINLOSSREASON, RECORDCREATEDBY, REVCOMMITSTATUSDESCR, REVENUESTATUSDESCR, PARENTEXPENSEALLOC, TRANSACTIONLINES.ACCOUNTINGIMPACT.ACCOUNTINGBOOK, AMOUNTUNBILLED, OPPORTUNITY^TRANSACTION.ENTITYSTATUS, CONTRACTCOSTAMOUNT, CONTRACTDEFERREDEXPENSEACCT, CONTRACTEXPENSEACCT, CONTRACTEXPENSESOURCEACCT, CREATEDDATE, CREATEDBY, TRANSACTIONLINES.CREATEDFROM, ACTUALPRODUCTIONENDDATE, ACTUALPRODUCTIONSTARTDATE, BIDCLOSEDATE, BIDOPENDATE, OLDBIDOPENDATE, CONTRACTCOSTACCRUALDATE, <SEE LAST_MODIFIED_DATE>, TAXPOINTDATE, DUEDATE, ENTITY, ENTITYTAXREGNUM, EXCHANGERATE, INCLUDEINFORECAST, ISACTUALPRODENDDATEENTEREDMANUALLY, ISACTUALPRODSTARTDATEENTEREDMANUALLY, ADVANCEDINTERCOMPANY, COMPLIANT, ISCROSSSUBTRANSACTION, ISFINCHRG, ISINTRANSITPAYMENT, MERGEDINTONEWARRANGEMENTS, POSTING, TAXPOINTDATEOVERRIDE, ISWIP, JOB, <EXPOSED ON TRANSACTIONLINE>, -, PRICINGTIERS, OPENINGBALANCETRANSACTION, OTHERREFNAME, PREVDATE, TRANSACTIONSHIPMENTS.SHIPPINGMETHOD, EXTERNALID, TRANNUMBERDISPLAYNAME, TRANSFERLOCATION

TRANSACTIONLINE:
  TRANSACTION, EXPENSEACCOUNT, AMOUNT, FXAMOUNTLINKED, AMOUNTLINKED, CLASS, ENTITY, CLEAREDDATE, CLOSEDATE, LINELASTMODIFIEDDATE, DEPARTMENT, DONOTDISPLAYLINE, CATEGORY, GROSSAMT, HASCOSTLINE, ISCOGS, ISCUSTOMGLLINE, EXCLUDEFROMRATEREQUEST, ISBILLABLE, CLEARED, ISNONREIMBURSABLE, TAXLINE, QUANTITY, ITEM, ISCLOSED, RATE, KITMEMBEROF, LOCATION, MEMO, NETAMOUNT, QUANTITYBILLED, QUANTITYREVCOMMITTED, TRANSACTIONDISCOUNT, ID, LINESEQUENCENUMBER, PAYMENTMETHOD, PAYITEM, PERIODCLOSED, PRICE, QUANTITYSHIPRECV, DUEDATE, EXPECTEDSHIPDATE, ACTUALSHIPDATE, SUBSIDIARY, TAXCODE, ALTSALESAMT, SETTLEMENTAMOUNT, BILLINGSCHEDULE, BILLINGSUBSIDIARY, CATCHUPPERIOD, CHARGETYPE, COMPONENTYIELD, REQUESTEDDATE, DEFERREVREC, COSTESTIMATEBASE, COSTESTIMATE, EXPECTEDRECEIPTDATE, BASEGROSSAMT, ISREVRECTRANSACTION, ISFXVARIANCE, ISITEMVALUEADJUSTMENT, BLANDEDCOST, ISSCRAP, ISVSOEALLOC, ITEMSOURCE, MATCHBILLTORECEIPT, MNETALTSALESAMOUNT, NEEDSREVENUEELEMENT, ORDERALLOCATIONSTRATEGY, ORDERPRIORITY, PROJECTTASK, QUANTITYCOMMITTED, REIMBURSEMENTTYPE, AMORTIZATIONENDDATE, REVRECENDDATE, AMORTIZSTARTDATE, REVRECSTARTDATE, REVENUEELEMENT, AMORTIZATIONSCHED, REVRECSCHEDULE, SOURCESUBSIDIARY, SUBSCRIPTIONLINE, TAXTYPE, REVRECTERMINMONTHS, TRANSFERORDERITEMLINEID, TRANSACTIONLINETYPE, UNIQUEKEY, UNITS, VSOEDELIVERED

ITEM:
  CONVERSIONRATE, FEATUREDDESCRIPTION, LOWERWARNINGLIMIT, SECONDARYUNITSTYPE, STOREDESCRIPTION, STOREDETAILEDDESCRIPTION, STOREDISPLAYNAME, STOREDISPLAYNAMEORIG, UPPERWARNINGLIMIT, QUANTITYONORDER, DISPLAYNAME, EXPENSEACCOUNT, FULLNAME, ISINACTIVE, EXTERNALID, ID, LASTINVENTORYCOSTINGCORRECTIONDATE, METATAGHTML, ITEMID, RATEINCLUDINGTAX, PURCHASEORDERAMOUNT, PURCHASEORDERQUANTITY, PURCHASEORDERQUANTITYDIFF, RECEIPTAMOUNT, RECEIPTQUANTITY, RECEIPTQUANTITYDIFF, SAFETYSTOCKLEVELDAYS, DESCRIPTION, ITEMTYPE, VENDOR

ACCOUNT:
  EXTERNALID, ID, ACCTNUMBER, CLASS, LASTMODIFIEDDATE, DEPARTMENT, ELIMINATE, REVALUE, ISSUMMARY, ISINACTIVE, LOCATION, ACCTNAME, BALANCE, ACCTTYPE

SUBSIDIARY:
  CURRENCY, COUNTRY, LASTMODIFIEDDATE, EDITION, FEDERALIDNUMBER, FISCALCALENDAR, ISELIMINATION, ISINACTIVE, STATUS, LEGALNAME, NAME / FULLNAME, ID, DROPDOWNSTATE, STATE, STATE1TAXNUMBER, TAXREGISTRATION, URL

DEPARTMENT:
  LASTMODIFIEDDATE, EXTERNALID, ID, PARENT, SUBSIDIARY

LOCATION:
  LASTMODIFIEDDATE, MAKEINVENTORYAVAILABLESTORE, INCLUDEINSUPPLYPLANNING, EXTERNALID, ID, PARENT, TRANPREFIX, SUBSIDIARY

CONTACT:
  CONTACTSOURCECAMPAIGNCATEGORY, ADDRESSBOOK, ALTEMAIL, ASSISTANT, ASSISTANTPHONE, COMMENTS, COMPANY, EXTERNALID, ID, DATECREATED, LASTMODIFIEDDATE, EMAIL, FAX, FIRSTNAME, FULLNAME, HOMEPHONE, ISPRIVATE, EMAILPREFERENCE, ISINACTIVE, LASTNAME, MIDDLENAME, MOBILEPHONE, ENTITYID, OFFICEPHONE, PHONE, SALUTATION, SUPERVISOR, SUPERVISORPHONE, TITLE, NAMEORIG, ENTITYTITLE

ENTITY:
  DATECREATED, LASTMODIFIEDDATE, EMAIL, EXTERNALID, ID, TYPE, FIRSTNAME, FULLNAME, GLOBALSUBSCRIPTIONSTATUS, ISINACTIVE, ISUNAVAILABLE, LASTNAME, MIDDLENAME, ENTITYID, COMMENTS, SOURCE, PARENT, PHONE, SALUTATION, LABORCOST, NAMEORIG, CONTACT, CONTACTRESTRICTION, CUSTOMER, CUSTOMERONPROJECTRESTRICTION, CUSTOMERRESTRICTION, EMPLOYEE, EMPLOYEERESTRICTION, ENTITYGROUPRESTRICTION, GENERICRESOURCE, GROUP, OTHERNAME, PARTNER, PARTNERRESTRICTION, PROJECT, PROJECTTEMPLATE, VENDOR, ENTITYTITLE

JOB:
  ALLOWTASKTIMEFORRSRCALLOC, COMPANYNAME, DATECREATED, EXTERNALID, ID, LASTMODIFIEDDATE, USEALLOCATEDTIMEFORFORECAST, FORECASTCHARGERUNONDEMAND, PROJECTCOMPLETELYBILLED, SOURCESERVICEITEMFROMRATECARD, ISINACTIVE, PARENT, PROJECTMANAGER, PROJECTEDENDDATE, ESTIMATEREVRECTEMPLATE, ESTIMATEDREVENUE, SCHEDULINGMETHOD, TIMEAPPROVAL, USEPERCENTCOMPLETEOVERRIDE, NAMEORIG, ENTITYTITLE

CURRENCY:
  SYMBOL, EXTERNALID, ID, LASTMODIFIEDDATE, ISINACTIVE, NAME, CURRENCYPRECISION

COUNTRY:
  UNIQUEKEY, NAME, ID

OTHER AVAILABLE TABLES:

-:
  -

ACCOUNTINGBOOK:
  EXTERNALID, BASEBOOK, LASTMODIFIEDDATE, EFFECTIVEPERIOD, ISADJUSTMENTONLY, ISCONSOLIDATED, CONTINGENTREVENUEHANDLING, ISPRIMARY, TWOSTEPREVENUEALLOCATION, UNBILLEDRECEIVABLEGROUPING

ACCOUNTINGBOOKSUBSIDIARIES:
  EFFECTIVEPERIOD, CURRENCY, EXCHANGERATE, SUBSIDIARY

ACCOUNTINGBOOKSUBSIDIARYMAP:
  SUBSIDIARY

ACCOUNTINGPERIOD:
  CLOSED, APLOCKED, ARLOCKED, ALLLOCKED, CLOSEDONDATE, PAYROLLLOCKED, LASTMODIFIEDDATE, ENDDATE, ISADJUST, ISINACTIVE, PERIODNAME, PARENT, ISQUARTER, STARTDATE, ISYEAR

ACCOUNTINGPERIODFISCALCALENDARS:
  FISCALCALENDAR, PARENT

ACCOUNTSUBSIDIARYMAP:
  ACCOUNT, SUBSIDIARY

ACCOUNTTYPE:
  BALANCESHEET, LEFT

ACTIVITY:
  ID, SUPPORTCASE, CONTACT, COMPLETEDDATE, CREATEDDATE, LASTMODIFIEDDATE, STATUS, TITLE, TYPE

ADDRESSBOOK:
  INTERNALID, ENTITY

ADMISSIBILITYPACKAGETYPE:
  NAME

AGGREGATEITEMLOCATION:
  ATPLEADTIME, QUANTITYAVAILABLE, AVERAGECOSTMLI, BACKWARDCONSUMPTIONDAYS, DEFAULTRETURNCOST, DEMANDTIMEFENCE, FIXEDLOTSIZE, FORWARDCONSUMPTIONDAYS, INVENTORYCOSTTEMPLATE, INVTCLASSIFICATION, INVTCOUNTINTERVAL, ITEM, LASTINVTCOUNTDATE, LOCATION, NEXTINVTCOUNTDATE, LEADTIME, QUANTITYONHAND, ONHANDVALUEMLI, QUANTITYONORDER, PERIODICLOTSIZEDAYS, ...

ALLOCATEDDEMAND:
  TRANSACTION, ORDER, ORDERSTATUS, TRANLINE, DEMANDLINEKEY, SALESCHANNEL

ALLOCATEDSUPPLY:
  TRANSACTION, TRANLINE, SALESCHANNEL

AMORTIZATIONSCHEDULE:
  ACCOUNTINGBOOK, ENDDATE, STARTDATE

AMORTIZATIONSCHEDULERECURRENCE:
  DEFREVACCOUNT, POSTINGPERIOD, ISRECOGNIZED, JOURNAL_ID, AMORTIZATIONSCHEDULE, JDATE

AMORTIZATIONTEMPLATERECURRENCE:
  DEFREVACCOUNT, AMORTIZATIONTEMPLATE

ASCHARGEDPROJECTREVENUERULEPROJECTREVENUERLCHARGERL:
  ACTUALAMOUNT, CHARGERULE, PROJECTREVENUERULE

ASSEMBLYBOMLOCATION:
  BILLOFMATERIALS

ASSEMBLYITEMBOM:
  ASSEMBLY, BILLOFMATERIALS, MEMO

ASSEMBLYITEMCORRELATEDITEM:
  ITEMNKEYFLD

ASSEMBLYITEMIMAGE:
  ITEM

ASSEMBLYITEMITEMACCOUNTINGBOOKDETAIL:
  ITEM

ASSEMBLYITEMITEMQUANTITYPRICINGLEVEL:
  ITEM

ASSEMBLYITEMITEMVENDOR:
  PURCHASEPRICE

ASSEMBLYITEMLOCATIONS:
  ATPLEADTIME, QUANTITYAVAILABLE, BACKWARDCONSUMPTIONDAYS, DEFAULTRETURNCOST, DEMANDTIMEFENCE, FIXEDLOTSIZE, FORWARDCONSUMPTIONDAYS, INVENTORYCOSTTEMPLATE, INVTCLASSIFICATION, INVTCOUNTINTERVAL, LASTINVTCOUNTDATE, NEXTINVTCOUNTDATE, LEADTIME, QUANTITYONHAND, ONHANDVALUEMLI, QUANTITYONORDER, PERIODICLOTSIZEDAYS, REORDERPOINT, RESCHEDULEINDAYS, RESCHEDULEOUTDAYS, ...

ASSEMBLYITEMMEMBER:
  COMPONENTYIELD, EFFECTIVEREVISION, ID, ITEMSOURCE, OBSOLETEREVISION, PARENTITEM, WEIGHT

ASSEMBLYITEMPRICE:
  DISCOUNT, DISCOUNTDISPLAY, ISINACTIVE, ISONLINE, PRICELEVEL, PRICELEVELNAME, CURRENCYPAGE

ASSEMBLYITEMQUANTITY:
  ITEM, ID, SEQNUM, MAXCOUNT, MINCOUNT

ASSEMBLYITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

ATPMETHODTYPE:
  NAME

ATTENDEE:
  ATTENDEE, CALENDAREVENT, RESPONSE

BILLINGACCOUNT:
  BILLADDRESSLIST, EXTERNALID, ID, MEMO, NAME, IDNUMBER, BILLINGSCHEDULE, CLASS, CURRENCY, CUSTOMER, CREATEDDATE, LASTBILLDATE, LASTBILLCYCLEDATE, LASTMODIFIEDDATE, STARTDATE, DEPARTMENT, REQUESTOFFCYCLEINVOICE, CUSTOMERDEFAULT, ORIGCUSTOMERDEFAULT, INACTIVE, ...

BILLINGCLASS:
  EXTERNALID, ID, DESCRIPTION, ISINACTIVE, NAME, SALEUNIT, UNITSTYPE

BILLINGCLASSPRICECOST:
  BILLINGCLASS, PRICE

BILLINGRATECARD:
  EXTERNALID, ID, CUSTOMER, CREATEDDATE, LASTMODIFIEDDATE, ISINACTIVE, NAME, DELETEVERSION

BILLINGRATECARDPRICEFORSEARCH:
  BILLINGCLASS

BILLINGRATECARDPRICEMULTIFORSEARCH:
  BILLINGCLASS

BILLINGRATECARDVERSION:
  BILLINGRATECARD, CREATEDDATE, EFFECTIVEDATE, LASTMODIFIEDDATE, VERSION

BILLINGSCHEDULE:
  ID, SCHEDULETYPE, FREQUENCY, NAME, NUMBERREMAINING

BILLINGSCHEDULETYPE:
  NAME

BILLOFDISTRIBUTION:
  EXTERNALID, ID, DISTRIBUTIONCATEGORY, DISTRIBUTIONNETWORK, LOCATION

BILLVARIANCESTATUS:
  NAME

BIN:
  ID, BINNUMBER, EXTERNALID, LOCATION, MEMO

BLANKETPURCHASEORDEREXPENSEMACHINE:
  EXPENSEITEM

BOM:
  AVAILABLEFORALLASSEMBLIES, AVAILABLEFORALLLOCATIONS, EXTERNALID, ID, CREATEDDATE, INCLUDECHILDREN, ISINACTIVE, MEMO, NAME, LEGACYBOMFORASSEMBLY, USECOMPONENTYIELD

BOMREVISION:
  BILLOFMATERIALS, EXTERNALID, ID, CREATEDDATE, EFFECTIVESTARTDATE, EFFECTIVEENDDATE, ISINACTIVE, MEMO, NAME

BOMREVISIONBOMMAP:
  BILLOFMATERIALS, BOMREVISION

BOMREVISIONCOMPONENT:
  ID, BOMREVISION, COMPONENTYIELD, ITEMSOURCE, LINEID

BOMREVISIONCOMPONENTMEMBER:
  ID, ITEM, ITEMSOURCE

BUDGETCATEGORY:
  ID, BUDGETTYPE, NAME

BUDGETEXCHANGERATE:
  ACCOUNTINGBOOK, POSTINGPERIOD, AVERAGERATE, ID, CURRENTRATE, FROMSUBSIDIARY, HISTORICALRATE, TOSUBSIDIARY, FROMCURRENCY, TOCURRENCY

BUDGETLEGACY:
  ACCOUNT, ACCOUNTINGBOOK, PERIOD, AMOUNT, ID, CATEGORY, CLASS, CUSTOMER, DEPARTMENT, ITEM, LOCATION, SUBSIDIARY

BUDGETSMACHINE:
  AMOUNT, BUDGETID

BUDGETSMACHINENOACCOUNTINGPERIOD:
  AMOUNT

CALENDAREVENT:
  RESPONSE, ACCESSLEVEL, COMPANY, CONTACT, STARTDATE, CREATEDDATE, LASTMODIFIEDDATE, EXTERNALID, ID, TIMEDEVENT, LOCATION, MESSAGE, TRANSACTION, ORGANIZER, STATUS, SUPPORTCASE, TITLE

CAMPAIGN:
  CREATEDDATE, LASTMODIFIEDDATE

CAMPAIGNAUDIENCE:
  EXTERNALID, ID

CAMPAIGNCATEGORY:
  EXTERNALID, ID, LEADSOURCE, ISEXTERNAL, PARENT

CAMPAIGNCHANNEL:
  EXTERNALID, ID, EVENTTYPE

CAMPAIGNEVENT:
  CAMPAIGN, CHANNEL, COST, DSCHEDULED, CAMPAIGNGROUP, PROMOCODE, SUBSCRIPTION, TEMPLATE

CAMPAIGNFAMILY:
  EXTERNALID, ID

CAMPAIGNOFFER:
  EXTERNALID, ID

CAMPAIGNRESPONSE:
  LEADSOURCE, CHANNEL, CAMPAIGNEVENT, ID, CAMPAIGNRESPONSEDATE, ENTITY, RESPONSE

CAMPAIGNRESPONSEHISTORYENTRY:
  AUTHOR, CAMPAIGNRESPONSE, RESPONSEDATE, NOTE, RESPONSE

CAMPAIGNSEARCHENGINE:
  EXTERNALID, ID

CAMPAIGNSUBSCRIPTION:
  ID

CAMPAIGNTEMPLATE
EMAILTEMPLATE
FAXTEMPLATE
MAILTEMPLATE
ONLINEFORMTEMPLATE
SYSTEMEMAILTEMPLATE:
  ID, MODIFIEDBY, RECORDTYPE, LASTMODIFIEDDATE, FROMEMAIL, ISINACTIVE, ISPRIVATE, OWNER, REPLYTOEMAIL

CAMPAIGNVERTICAL:
  EXTERNALID, ID

CASHREFUNDBILLINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

CASHREFUNDSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

CASHREFUNDTRANPROMOTION:
  DISCOUNTISTAXABLE

CASHSALEBILLINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

CASHSALEGIFTCERTREDEMPTION:
  AUTHCODE

CASHSALEITEMSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

CASHSALESHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

CASHSALETRANPROMOTION:
  DISCOUNTISTAXABLE

CATEGORY1099MISC:
  NAME, THRESHOLD

CCBCCRECIPIENT:
  OTHERRECIPIENT, MESSAGE

CENTERTYPE:
  CENTERTYPE, NAME

CHARGE:
  BILLINGSCHEDULEFROMSOLINE, AMOUNT, PREVIOUSAMOUNT, BILLINGACCOUNT, BILLINGMODE, BILLINGSCHEDULE, EXTERNALID, ID, CHARGEEMPLOYEE, RULE, STAGE, CHARGETYPE, USE, CLASS, CURRENCY, BILLTO, CHARGEDATE, BILLDATE, LASTMODIFIEDDATE, SERVICEENDDATE, ...

CHARGERULE:
  BILLINGRATECARD, RATESOURCETYPE

CHECKEXPENSEMACHINE:
  EXPENSEITEM

CHECKPAYEEADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

CLASS:
  ID

CLASSIFICATION:
  EXTERNALID, LASTMODIFIEDDATE, PARENT, SUBSIDIARY, ID

CLASSIFICATIONSUBSIDIARYMAP:
  SUBSIDIARY, CLASSIFICATION

COMPANYADDRESSBOOK:
  INTERNALID, ADDRESSBOOKADDRESS, ADDRESSBOOKADDRESS_KEY, ENTITY, DEFAULTBILLING, DEFAULTSHIPPING, LABEL

COMPANYADDRESSBOOKENTITYADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

COMPANYBULKMERGE:
  STATUS

COMPANYCAMPAIGNS:
  CAMPAIGNEVENT, DATESENT, CAMPAIGNTEMPLATEID, CAMPAIGNRESPONSEID, RESPONSE, CONTACT, ENTITY, CATEGORY, TITLE

COMPANYCONTACTRELATIONSHIP:
  COMPANY, CONTACT, ROLE, LASTMODIFIEDDATE

COMPETITOR:
  EXTERNALID, ID, LASTMODIFIEDDATE, DESCRIPTION, ISINACTIVE, NAME, PRODUCTSERVICE, STRATEGY, STRENGTHS, URL, WEAKNESSES

COMPETITOROPPORTUNITY:
  COMPETITOR, WINNER, NOTES, OPPORTUNITY

CONSOLIDATEDEXCHANGERATE:
  ACCOUNTINGBOOK, POSTINGPERIOD, AVERAGERATE, ID, CURRENTRATE, FROMSUBSIDIARY, HISTORICALRATE, TOSUBSIDIARY, FROMCURRENCY, TOCURRENCY

CONTACT, ENTITYADDRESS:
  CITY, COUNTRY, ADDR1, ADDR2, ADDR3, STATE, ZIP

CONTACTADDRESSBOOK:
  INTERNALID, ADDRESSBOOKADDRESS, ADDRESSBOOKADDRESS_KEY, ENTITY, DEFAULTBILLING, DEFAULTSHIPPING, LABEL

CONTACTADDRESSBOOKENTITYADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

CONTACTBULKMERGE:
  STATUS

CONTACTCATEGORY:
  ISINACTIVE, NAME, PRIVATE

CONTACTCONTACTCAMPAIGNS:
  CAMPAIGNEVENT, DATESENT, CAMPAIGNTEMPLATEID, CAMPAIGNRESPONSEID, RESPONSE, CONTACT, ENTITY, CATEGORY, ENTITYORCONTACT, TITLE

CONTACTCONTACTTYPEMAP:
  CONTACT

CONTACTROLE:
  EXTERNALID, ID, ISINACTIVE, NAME

CONTACTSUBSCRIPTIONS:
  LASTMODIFIEDDATE

COSTCATEGORY:
  NAME

COSTESTIMATETYPE:
  NAME

COUPONCODE:
  CODE, ID, DATESENT, PROMOTION, RECIPIENT

CREATIONTRIGGEREDBYEVENT:
  REVENUEPLAN, EVENTSOURCENAME

CREDITCARDCHARGEEXPENSEMACHINE:
  EXPENSEITEM

CREDITCARDREFUNDEXPENSEMACHINE:
  EXPENSEITEM

CREDITMEMOBILLINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

CREDITMEMOITEMSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

CREDITMEMOSHIPGROUP:
  HANDLINGLINEID, DOC

CREDITMEMOSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

CREDITMEMOTRANPROMOTION:
  DISCOUNTISTAXABLE

CROSSCHARGEJOURNALTRANSACTIONPAYMENTS:
  PARENTTRANSACTION

CURRENCY EXCHANGE RATE:
  ANCHORCURRENCY, BASECURRENCY, TRANSACTIONCURRENCY, ID, RATEPROVIDER, CURRENCYRATETYPE, EFFECTIVEDATE, LASTMODIFIEDDATE, LASTMODIFIEDBY, EXCHANGERATE, FXSOURCEMETHOD

CURRENCYRATETYPE:
  EXTERNALID, ID, DESCRIPTION, ISDEFAULT, NAME

CUSTOMERADDRESSBOOK:
  INTERNALID, ADDRESSBOOKADDRESS, ADDRESSBOOKADDRESS_KEY, ADDRESS, ENTITY, DEFAULTBILLING, DEFAULTSHIPPING, LABEL

CUSTOMERADDRESSBOOKENTITYADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

CUSTOMERBULKMERGE:
  STATUS

CUSTOMERCAMPAIGNS:
  CAMPAIGNEVENT, DATESENT, CAMPAIGNTEMPLATEID, CAMPAIGNRESPONSEID, RESPONSE, CONTACT, ENTITY, CATEGORY, TITLE

CUSTOMERCATEGORY:
  EXTERNALID, ID, LASTMODIFIEDDATE, ISINACTIVE, NAME, PARENT

CUSTOMERCONTACTROLE:
  ENTITY, ROLE, CONTACTNAME

CUSTOMERGROUPPRICING:
  CUSTOMER, LEVEL, GROUP

CUSTOMERITEMPRICING:
  CURRENCY, CUSTOMER, ITEM, LEVEL

CUSTOMERPARTNER:
  CONTRIBUTION, ID, ISPRIMARY, PARTNER, PARTNERROLE

CUSTOMERPROJECT:
  EXTERNALID, ENTITYID, ID

CUSTOMERREFUNDPAYEEADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

CUSTOMERSALESTEAM:
  CONTRIBUTION, CUSTOMER, ISPRIMARY, EMPLOYEE, SALESROLE

CUSTOMERSUBSCRIPTIONS:
  LASTMODIFIEDDATE

CUSTOMERSUBSIDIARYRELATIONSHIP:
  BALANCE, DEPOSITBALANCE, UNBILLEDORDERS

DATESFIXEDAMOUNT:
  RECOGNITIONDATE, FIXEDAMOUNT, ROWKEY, PROJECTREVENUERULE

DATESPCTFROMTOTAL:
  RECOGNITIONDATE, PERCENTFROMTOTAL, ROWKEY, PROJECTREVENUERULE

DELETEDRECORD:
  RECORDTYPEID, DELETEDDATE, DELETEDBY, ISCUSTOMLIST, NAME, TYPE, RECORDID

DEPARTMENTSUBSIDIARYMAP:
  DEPARTMENT, SUBSIDIARY

DESCRIPTIONITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

DISCOUNTITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

DISTRIBUTIONCATEGORY:
  NAME, ID, ISINACTIVE

DISTRIBUTIONNETWORK:
  EXTERNALID, ID, MEMO, NAME

DOWNLOADITEMCORRELATEDITEM:
  ITEMNKEYFLD

DOWNLOADITEMIMAGE:
  ITEM

DOWNLOADITEMITEMACCOUNTINGBOOKDETAIL:
  ITEM

DOWNLOADITEMITEMQUANTITYPRICINGLEVEL:
  ITEM

DOWNLOADITEMPRICE:
  DISCOUNT, DISCOUNTDISPLAY, ISINACTIVE, ISONLINE, PRICELEVEL, PRICELEVELNAME, CURRENCYPAGE

DOWNLOADITEMQUANTITY:
  ITEM, ID, SEQNUM, MAXCOUNT, MINCOUNT

DOWNLOADITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

EFFECTIVEROLESUBSIDIARYRESTRICTIONMAP:
  ROLE, SUBSIDIARY

EMPLOYEEADDRESSBOOK:
  INTERNALID, ADDRESSBOOKADDRESS, ADDRESSBOOKADDRESS_KEY, ENTITY, DEFAULTBILLING, DEFAULTSHIPPING, LABEL

EMPLOYEEADDRESSBOOKENTITYADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

EMPLOYEEBULKMERGE:
  STATUS

EMPLOYEECAMPAIGNS:
  CAMPAIGNEVENT, DATESENT, CAMPAIGNTEMPLATEID, CAMPAIGNRESPONSEID, RESPONSE, CONTACT, ENTITY, CATEGORY, TITLE

EMPLOYEECORPORATECARDS:
  EMPLOYEE, CORPORATECARDPROFILE

EMPLOYEEEARNING:
  PINAMELINKED

EMPLOYEEEXPENSEREPORTCURRENCIES:
  CURRENCY, EMPLOYEE

EMPLOYEEEXPENSESOURCETYPE:
  DESCRIPTION, EXTERNALID, NAME, ID

EMPLOYEELISTAUDIENCE:
  SITECATEGORY

EMPLOYEEROLES:
  ENTITY, SELECTEDROLE

EMPLOYEEROLESFORSEARCH:
  ENTITY, ROLE

EMPLOYEESTATUS:
  NAME

EMPLOYEESUBSCRIPTIONS:
  LASTMODIFIEDDATE

EMPLOYEETYPE:
  ID, NAME

ENTITYADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

ENTITYADDRESSBOOK:
  INTERNALID, ADDRESSBOOKADDRESS, ADDRESSBOOKADDRESS_KEY, ADDRESS, LASTMODIFIEDDATE, ENTITY, DEFAULTBILLING, DEFAULTSHIPPING, LABEL

ENTITYBULKMERGE:
  STATUS

ENTITYGROUP:
  ID, TYPE, ISMANUFACTURINGWORKCENTER, ISPRIVATE, ISSALESREP, ISSUPPORTREP, LABORRESOURCES, MACHINERESOURCES, GROUPOWNER, GROUPNAME, WORKCALENDAR, LASTMODIFIEDDATE, SUBSIDIARY

ENTITYGROUPBULKMERGE:
  STATUS

ENTITYGROUPCAMPAIGNS:
  CAMPAIGNEVENT, DATESENT, GROUP, CAMPAIGNTEMPLATEID, CAMPAIGNRESPONSEID, RESPONSE, CONTACT, ENTITY, CATEGORY, TITLE

ENTITYGROUPMEMBER:
  CONTACTMEMBER, CUSTJOBMEMBER, EMPLOYEEMEMBER, JOBMEMBER, MEMBER, PARTNERMEMBER, VENDORMEMBER, GROUP, ISPRIMARY, ISINACTIVE, NAME

ENTITYNOTE:
  ENTITY

ENTITYSTATUS:
  EXTERNALID, KEY, MODIFIED, DESCR, INACTIVE, NAME, PROBABILITY, READONLY, ENTITYTYPE

ESCALATIONTERRITORYENTITY AND SUPPORTTERRITORYENTITY:
  EMAIL, PHONE, ENTITY, TERRITORY

ESTIMATEBILLINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

ESTIMATEITEMSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

ESTIMATESHIPGROUP:
  HANDLINGLINEID, DOC

ESTIMATESHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

ESTIMATETRANPROMOTION:
  DISCOUNTISTAXABLE

EVENTPRIORITY:
  NAME

EXPENSEAMORTIZATIONRULE:
  CONTRAACCOUNT, CREATEDDATE, LASTMODIFIEDDATE, ID, NAME, PERIODOFFSET, RECOGNITIONPERIOD, STARTOFFSET, TERMINDAYS, TERMINMONTHS

EXPENSECATEGORY:
  DESCRIPTION, EXPENSEACCT, EXTERNALID, ID, EXPENSEITEM, PERSONALCORPORATECARDEXPENSE, ISINACTIVE, RATEREQUIRED

EXPENSECATEGORYRATE:
  DEFAULTRATE, EXPENSECATEGORY, SUBSIDIARY

EXPENSECATEGORYSUBSIDIARYMAP:
  CATEGORY, SUBSIDIARY

EXPENSEITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

EXPENSEMACHINE:
  EXPENSEITEM, RATEREQUIRED, AMOUNT, CURRENCY, EXCHANGERATE, CATEGORY, EXPENSEDATE, ID, FOREIGNAMOUNT, RECEIPT, CORPORATECREDITCARD, MEMO, QUANTITY, REFNUMBER, EXPENSEREPORT, LINE

EXPENSEPLAN:
  CATCHUPPERIOD, COMMENTS, LASTMODIFIEDDATE, REVRECENDDATE, REVENUERECOGNITIONRULE, HOLDREVENUERECOGNITION, ID, RECORDNUMBER, RESIDUAL, REVRECSTARTDATE, ITEM, RELATEDREVENUEELEMENT, CREATIONTRIGGEREDBYDISPLAY, ACCOUNTINGBOOK

EXPENSEPLANPLANNEDEXPENSE:
  DATEEXECUTED

FAIRVALUEFORMULA:
  NAME

FAIRVALUEPRICE:
  CURRENCY, ENDDATE, EXTERNALID, ID, ISVSOEPRICE, ITEM, STARTDATE, UNITS, FAIRVALUE, UNITSTYPE

FAIRVALUERANGEPOLICY:
  NAME

FIXEDAMOUNTPROJECTREVENUERULEPROJECTREVENUERLCHARGERL:
  ACTUALAMOUNT, CHARGERULE, PROJECTREVENUERULE

FORECAST:
  AMOUNT, STARTDATE, ID, AMOUNTHIGH, ASA, FORECASTLOW, SALESREP, SUBSIDIARY, TEAM

FORECASTTYPE:
  SNAME

FREQUENCYTYPE:
  LONGNAME

FULFILLMENTREQUEST:
  CREATEDDATE, LASTMODIFIEDDATE, TRANDATE, EXTERNALID, ID

FULFILLMENTREQUESTITEM:
  UNITS, ITEMKEY, ITEMNAME, ITEMNAME_SELECTOR, SITEMNAME, COUNTRYOFMANUFACTURE, ITEMHANDLINGCOST, ISHAZMATITEM, HAZMATHAZARDCLASS, HAZMATID, HAZMATITEMUNITS, HAZMATITEMUNITSQTY, HAZMATPACKINGGROUP, HAZMATSHIPPINGNAME, ONHAND, ISSERIAL, ITEMSUBTYPE, ITEMUPC, ITEMWEIGHT, DESCRIPTION, ...

FULLSUBSIDIARYHIERARCHY:
  CURRENCY, FISCALCALENDAR, ISELIMINATION, PARENT, EXTERNALID

GENERALIZEDITEM:
  ID, NAME, ORIGPARENT, PARENT, EXTERNALID

GENERICCAMPAIGNITEM:
  CAMPAIGN, ITEM

GENERICRESOURCE:
  BILLINGCLASS, LASTMODIFIEDDATE, ID, ISINACTIVE, LABORCOST, LABORPRICE, ENTITYID, SUBSIDIARY, WORKCALENDAR

GIFTCERTIFICATE:
  ORIGINALAMOUNT, AMOUNTREMAINING, EXPIRATIONDATE, SENDER, GIFTCERTCODE, ID, MESSAGE, EMAIL, NAME, INTERNALID

GIFTCERTIFICATEITEMCORRELATEDITEM:
  ITEMNKEYFLD

GIFTCERTIFICATEITEMIMAGE:
  ITEM

GIFTCERTIFICATEITEMPRICE:
  DISCOUNT, DISCOUNTDISPLAY, ISINACTIVE, ISONLINE, PRICELEVEL, PRICELEVELNAME, CURRENCYPAGE

GIFTCERTIFICATEITEMQUANTITY:
  ITEM, ID, SEQNUM, MAXCOUNT, MINCOUNT

GIFTCERTIFICATEITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

GIRCUSTOMERRETURNLOCATION:
  CITY, COUNTRY, STATE

GIRFULFILLMENTLOCATION:
  CITY, COUNTRY, STATE

GLOBALACCOUNTMAPPING:
  ACCOUNTINGBOOK, ENDDATE, LASTMODIFIEDDATE, DESTINATIONACCOUNT, EXTERNALID, SOURCEACCOUNT, SUBSIDIARY

GLOBALINVENTORYRELATIONSHIP:
  EXTERNALID, ID, INVENTORYSUBSIDIARY, ALLLOCATIONSCUSTOMERRETURN, ALLLOCATIONSFULFILLMENT, ALLOWCROSSSUBCUSTOMERRETURN, ALLOWCROSSSUBFULFILLMENT, ORIGINATINGSUBSIDIARY

IMPORTEDEMPLOYEEEXPENSE:
  BILLEDAMOUNT, BILLEDCURRENCY, BILLEDTAXAMOUNT, CARDCURRENCY, COSTCENTER, CURRENCYEXCHANGERATE, CHARGEDATE, EMPLOYEE, CATEGORY, FORMATPROFILE, EXTERNALID, ID, CORPORATECARD, LOCALCHARGEAMOUNT, LOCALTAXAMOUNT, MEMO, SOURCETYPE, STATUS, TRANSACTIONID

INBOUNDSHIPMENT:
  BILLOFLADING, SHIPMENTBILLINGSTATUS, SHIPMENTBASECURRENCY, ACTUALDELIVERYDATE, ACTUALSHIPPINGDATE, EXPECTEDDELIVERYDATE, EXPECTEDSHIPPINGDATE, ID, SHIPMENTMEMO, SHIPMENTSTATUS, VESSELNUMBER

INBOUNDSHIPMENTITEM:
  CURRENCYPRECISION, SHIPMENTITEMTEXT, SHIPMENTITEMAMOUNT, POCURRENCY, SHIPMENTITEMEFFECTIVEDATE, SHIPMENTITEMEXCHANGERATE, FXRATE, INBOUNDSHIPMENT, ID, INCOTERM, ITEMID, ITEMTYPE, RECEIVINGLOCATION, UNIT, UNITRATE, VENDORID, WEIGHTLBS, SHIPMENTITEMDESCRIPTION

INBOUNDSHIPMENTITEM, UNITSTYPEUOM:
  UNIT_RATE

INBOUNDSHIPMENTITEM, VENDOR:
  VENDOR

INBOUNDSHIPMENTLANDEDCOST:
  LANDEDCOSTCURRENCYPRECISION

INBOUNDSHIPMENTLINK:
  TRANSACTIONLINEID

INCOTERM:
  NAME

INTERCOMPANYTRANSFERORDERSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

INVENTORYASSIGNMENT:
  TRANSACTION, QUANTITY, TRANSACTIONLINE

INVENTORYCOSTTEMPLATE:
  LASTMODIFIEDDATE, ID, MEMO, NAME

INVENTORYCOSTTEMPLATECOSTDETAIL:
  INVENTORYCOSTTEMPLATE, ITEM

INVENTORYITEMCORRELATEDITEM:
  ITEMNKEYFLD

INVENTORYITEMIMAGE:
  ITEM

INVENTORYITEMITEMACCOUNTINGBOOKDETAIL:
  ITEM

INVENTORYITEMITEMQUANTITYPRICINGLEVEL:
  ITEM

INVENTORYITEMITEMVENDOR:
  PURCHASEPRICE

INVENTORYITEMLOCATIONS:
  ATPLEADTIME, QUANTITYAVAILABLE, BACKWARDCONSUMPTIONDAYS, DEFAULTRETURNCOST, DEMANDTIMEFENCE, FIXEDLOTSIZE, FORWARDCONSUMPTIONDAYS, INVENTORYCOSTTEMPLATE, INVTCLASSIFICATION, INVTCOUNTINTERVAL, LASTINVTCOUNTDATE, NEXTINVTCOUNTDATE, LEADTIME, QUANTITYONHAND, ONHANDVALUEMLI, QUANTITYONORDER, PERIODICLOTSIZEDAYS, REORDERPOINT, RESCHEDULEINDAYS, RESCHEDULEOUTDAYS, ...

INVENTORYITEMPRICE:
  DISCOUNT, DISCOUNTDISPLAY, ISINACTIVE, ISONLINE, PRICELEVEL, PRICELEVELNAME, CURRENCYPAGE

INVENTORYITEMQUANTITY:
  ITEM, ID, SEQNUM, MAXCOUNT, MINCOUNT

INVENTORYITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

INVENTORYNUMBER:
  EXPIRATIONDATE, MEMO, ITEM, INVENTORYNUMBER

INVENTORYSTATUS:
  DESCRIPTION, EXTERNALID, ID, INVENTORYAVAILFORALLOC, INVENTORYAVAILABLE, STATE

INVOICEBILLINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

INVOICEGIFTCERTREDEMPTION:
  AUTHCODE

INVOICEINSTALLMENT:
  CURRENCY

INVOICEITEMSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

INVOICESHIPGROUP:
  HANDLINGLINEID, DOC

INVOICESHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

INVOICETRANPROMOTION:
  DISCOUNTISTAXABLE

INVTITEMPRICEHISTORY:
  DISCOUNT, CURRENCY, INTERNALID, ITEM, QUANTITY, PRICETYPE, VERSION

IPRESTRICTIONS:
  USER, ROLE

ISSUE:
  REPORTEDBY, EXTERNALID, ISSUEABSTRACT

ISSUEPRODUCTITEMMAP:
  ITEM

ITEMACCOUNTINGBOOKDETAIL:
  ITEM

ITEMACCOUNTMAPPING:
  ACCOUNTINGBOOK, ENDDATE, LASTMODIFIEDDATE, DESTINATIONACCOUNT, EXTERNALID, SOURCEACCOUNT, SUBSIDIARY

ITEMASSEMBLYITEMBOM:
  ASSEMBLY, BILLOFMATERIALS, MEMO

ITEMBASESUBSIDIARYMAP:
  ITEM, SUBSIDIARY

ITEMBINQUANTITY:
  LOCATION

ITEMCOLLECTION:
  DESCRIPTION, EXTERNALID, ID, NAME

ITEMCOLLECTIONITEMSIMPLEMAP:
  ITEMCOLLECTION, ITEM

ITEMCORRELATEDITEM:
  ITEMNKEYFLD

ITEMDEMANDPLAN:
  ALTERNATESOURCEITEM, LASTMODIFIEDDATE, ANALYSISDURATION, DEMANDPLANID, ID, ITEM, MEMO, PROJECTIONDURATION, PROJECTIONMETHOD, PROJECTIONSTARTDATE, SUBSIDIARY

ITEMDEMANDPLANDEMANDPLANDETAIL:
  ENDDATE, STARTDATE, ITEMDEMANDPLAN

ITEMDEMANDSOURCE:
  NAME

ITEMFULFILLMENTPACKAGE:
  PACKAGEDESCR, ITEMFULFILLMENT, PACKAGEWEIGHT

ITEMFULFILLMENTPACKAGEFEDEX:
  ALCOHOLRECIPIENTTYPEFEDEX, AUTHORIZATIONNUMBERFEDEX, CODAMOUNTFEDEX, CODOTHERCHARGEFEDEX, INSUREDVALUEFEDEX, DRYICEWEIGHTFEDEX, CODFREIGHTTYPEFEDEX, ISALCOHOLFEDEX, ISNONHAZLITHIUMFEDEX, ISNONSTANDARDCONTAINERFEDEX, PACKAGEHEIGHTFEDEX, PACKAGELENGTHFEDEX, PACKAGEWIDTHFEDEX, PRIORITYALERTCONTENTFEDEX, PRIORITYALERTTYPEFEDEX, REFERENCE1FEDEX, SIGNATURERELEASEFEDEX, PACKAGEWEIGHTFEDEX

ITEMFULFILLMENTPACKAGEUPS:
  CODAMOUNTUPS, PACKAGEDESCRUPS, INSUREDVALUEUPS, ADDITIONALHANDLINGUPS, PACKAGEHEIGHTUPS, PACKAGELENGTHUPS, PACKAGEWIDTHUPS, REFERENCE1UPS, REFERENCE2UPS, PACKAGEWEIGHTUPS

ITEMFULFILLMENTPACKAGEUSPS:
  PACKAGEDESCRUSPS, INSUREDVALUEUSPS, PACKAGEHEIGHTUSPS, PACKAGELENGTHUSPS, PACKAGEWIDTHUSPS, REFERENCE1USPS, REFERENCE2USPS, PACKAGEWEIGHTUSPS

ITEMFULFILLMENTRETURNADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

ITEMFULFILLMENTSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

ITEMGROUPMEMBER:
  ID, PARENTITEM, QUANTITY, WEIGHT

ITEMGROUPSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

ITEMIMAGE:
  ITEM

ITEMMEMBER:
  COMPONENTYIELD, EFFECTIVEREVISION, ID, ITEMSOURCE, OBSOLETEREVISION, PARENTITEM, QUANTITY, WEIGHT

ITEMPERIODICLOTSIZETYPE:
  NAME

ITEMPRICE:
  DISCOUNT, DISCOUNTDISPLAY, ISINACTIVE, ISONLINE, PRICELEVEL, PRICELEVELNAME, CURRENCYPAGE, DATELASTMODIFIED, PRICEQTY

ITEMQUANTITY:
  ITEM, ID, SEQNUM, MAXCOUNT, MINCOUNT

ITEMQUANTITYPRICINGLEVEL:
  ITEM

ITEMREVENUECATEGORY:
  NAME

ITEMREVISION:
  EFFECTIVEDATE, EXTERNALID, INACTIVE, ITEM, NAME, MEMO, OBSOLETEDATE

ITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

ITEMSUPPLYLOTSIZINGTYPE:
  NAME

ITEMSUPPLYPLAN:
  SUBSIDIARY, LASTMODIFIEDDATE, ITEM, ID, MEMO

ITEMSUPPLYPLANORDER:
  ORDERCREATED, ITEMSUPPLYPLAN, ORDERDATE, RECEIPTDATE, SOURCELOCATION

ITEMSUPPLYTYPE:
  NAME

ITEMTYPE:
  RESALABLE

ITEMVENDOR:
  PREFERREDVENDOR, ITEM, SUBSIDIARY, VENDORCODE, VENDOR, PURCHASEPRICE

ITEMVENDORPRICELINES:
  VENDORPRICE, VENDORCURRENCY

JOBADDRESSBOOK:
  INTERNALID, ADDRESSBOOKADDRESS, ADDRESSBOOKADDRESS_KEY, ENTITY, DEFAULTBILLING, DEFAULTSHIPPING, LABEL

JOBADDRESSBOOKENTITYADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

JOBBULKMERGE:
  STATUS

JOBRESOURCEJOBRESOURCEMAP:
  ROLE

JOBRESOURCEROLE:
  DESCRIPTION, OWNTIMEAPPROVAL, REASSIGNRESOURCES, PROJECTTIMEAPPROVER, ID, NAME, SENDMAILFORRATOFFCONFLICT

KITITEMCORRELATEDITEM:
  ITEMNKEYFLD

KITITEMIMAGE:
  ITEM

KITITEMITEMACCOUNTINGBOOKDETAIL:
  ITEM

KITITEMITEMQUANTITYPRICINGLEVEL:
  ITEM

KITITEMMEMBER:
  ID, PARENTITEM, QUANTITY, DROPSHIPMEMBER, WEIGHT

KITITEMPRICE:
  DISCOUNT, DISCOUNTDISPLAY, ISINACTIVE, ISONLINE, PRICELEVEL, PRICELEVELNAME, CURRENCYPAGE

KITITEMQUANTITY:
  ITEM, ID, SEQNUM, MAXCOUNT, MINCOUNT

KITITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

KNOWLEDGEBASEAUDIENCE:
  SITECATEGORY

LABORBASEDPROJECTREVENUERULEPROJECTREVENUERLCHARGERL:
  ACTUALAMOUNT, CHARGERULE, PROJECTREVENUERULE

LABORCOSTCARD:
  CURRENCY

LAGTYPE:
  NAME

LOCATIONCOSTINGGROUP:
  COSTINGGROUPCURRENCY, ID, NAME, MEMO

LOCATIONCOSTINGGROUPLOCATION:
  SUBSIDIARY, COSTINGGROUP

LOCATIONMAINADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

LOCATIONRETURNADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

LOCATIONSUBSIDIARYMAP:
  LOCATION, SUBSIDIARY

MANUFACTURINGCOMPLETIONOPERATIONARTBASE:
  WORKCENTER, OPERATIONSEQUENCE

MANUFACTURINGCOSTTEMPLATE:
  LASTMODIFIEDDATE, EXTERNALID, ID, MEMO, NAME

MANUFACTURINGCOSTTEMPLATECOSTDETAIL:
  ITEM, MANUFACTURINGCOSTTEMPLATE

MANUFACTURINGOPERATIONTASK:
  MANUFACTURINGWORKCENTER, MESSAGE, OPERATIONSEQUENCE, AUTOCALCULATELAG

MANUFACTURINGOPERATIONTASKCOSTDETAIL:
  ACCOUNT

MANUFACTURINGOPERATIONTASKPREDECESSOR:
  TYPE, MANUFACTURINGOPERATIONTASK

MANUFACTURINGROUTING:
  BILLOFMATERIALS, EXTERNALID, AUTOCALCULATELAG, ISDEFAULT, ITEM, ID, MEMO, NAME

MANUFACTURINGROUTINGCOMPONENT:
  OPERATIONDISPLAYTEXT, MANUFACTURINGROUTING

MANUFACTURINGROUTINGLOCATIONMAP:
  LOCATION

MANUFACTURINGROUTINGROUTINGSTEP:
  OPERATIONSEQUENCE, LAGAMOUNT, MANUFACTURINGCOSTTEMPLATE, MANUFACTURINGROUTING, MANUFACTURINGWORKCENTER, OPERATIONNAME, RUNRATE, SETUPTIME

MARKUPITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

MDRTESTCHECKPAYEEADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

MEMDOC:
  ACTION, SUBSEQUENTPOSTINGDATE, INDEFINITE, ID, NUMBERREMAINING, REPEATEVERY, SUBSEQUENT, TRANSACTIONTEMPLATE, UPDATEADDRESSES, UPDATEPRICES

MEMDOCTRANSACTIONTEMPLATEACCOUNTINGLINE:
  SUBSIDIARYBOOKCURRENCY, AMOUNT, CATCHUPPERIOD, REVRECENDDATE, REVRECSTARTDATE, DEFERREVREC, REVRECSCHEDULE, MEMDOCTRANSACTIONTEMPLATE, MEMDOCTRANSACTIONTEMPLATELINE

MEMDOCTRANSACTIONTEMPLATELINE:
  TRANSACTION, CLASS, ENTITY, DEPARTMENT, QUANTITY, ITEM, LOCATION, POSTING, TRANSACTIONDISCOUNT, ID, LINESEQUENCENUMBER, EXPECTEDSHIPDATE, TAXCODE, EXPECTEDRECEIPTDATE, SOURCESUBSIDIARY, TRANSACTIONLINETYPE, UNIQUEKEY

MEMDOCTRANSACTIONTEMPLATETRANPROMOTION:
  DISCOUNTISTAXABLE

MERGEARRANGEMENTHISTORY:
  REVENUEELEMENT

MESSAGE:
  AUTHOR, BCC, CC, ENTITY, DATETIME, LASTMODIFIEDDATE, ACTIVITY, AUTHOREMAIL, INTERNALONLY, EMAILED, INCOMING, MESSAGE, EXTERNALID, ID, MESSAGETYPE, RECIPIENT, PRIMARYRECIPIENT, RECORD, RECORDTYPE, SUBJECT, ...

MFGPLANNEDTIME:
  DATE, DURATION, MANUFACTURINGWORKCENTER, INTERNALID, MANUFACTURINGOPERATIONTASK

MFGPROJECTADDRESSBOOK:
  INTERNALID, ADDRESSBOOKADDRESS, ADDRESSBOOKADDRESS_KEY, ENTITY, DEFAULTBILLING, DEFAULTSHIPPING, LABEL

MFGPROJECTADDRESSBOOKENTITYADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

MFGPROJECTBULKMERGE:
  STATUS

MFGPROJECTJOBRESOURCESJOBRESOURCEJOBRESOURCEMAP:
  ROLE

MFGPROJECTPERCENTCOMPLETEOVERRIDE:
  PERIOD, COMMENTS, PERCENT

MFGPROJECTPROJECTBILLINGBUDGET:
  AMOUNT, CALCULATED, JOB

MFGPROJECTPROJECTCOSTBUDGET:
  AMOUNT, CALCULATED, JOB, CALCULATEDFROMALLOCATIONS

MONTHLYQUOTA:
  AMOUNT, ACLASS, PERIOD, DEPARTMENT, ENTITY, ASA, ITEM, LOCATION, QUARTERLYAMOUNT, ID, SUBSIDIARY, TEAMQUOTA

NETTINGSTATEMENTEXCHANGERATELINE:
  BASECURRENCY

NEXTTRANSACTIONACCOUNTINGLINELINK:
  AMOUNT

NEXTTRANSACTIONLINELINK:
  FOREIGNAMOUNT, NEXTLINE, LASTMODIFIEDDATE, QUANTITYLINKED

NEXTTRANSACTIONLINK:
  NEXTDOC, LINKTYPE

NEXUS:
  COUNTRY, DESCRIPTION, ISINACTIVE, TAXDATEFROMFULFILLMENT, ID, PARENTNEXUS, STATE, TAXAGENCY, TAXCODE, TAXAGENCYPST

NONINVENTORYITEMCORRELATEDITEM:
  ITEMNKEYFLD

NONINVENTORYITEMIMAGE:
  ITEM

NONINVENTORYITEMITEMACCOUNTINGBOOKDETAIL:
  ITEM

NONINVENTORYITEMITEMQUANTITYPRICINGLEVEL:
  ITEM

NONINVENTORYITEMITEMVENDOR:
  PURCHASEPRICE

NONINVENTORYITEMPRICE:
  DISCOUNT, DISCOUNTDISPLAY, ISINACTIVE, ISONLINE, PRICELEVEL, PRICELEVELNAME, CURRENCYPAGE

NONINVENTORYITEMQUANTITY:
  ITEM, ID, SEQNUM, MAXCOUNT, MINCOUNT

NONINVENTORYITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

NONINVENTORYPURCHASEITEMITEMACCOUNTINGBOOKDETAIL:
  ITEM

NONINVENTORYPURCHASEITEMITEMVENDOR:
  PURCHASEPRICE

NONINVENTORYPURCHASEITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

NONINVENTORYRESALEITEMCORRELATEDITEM:
  ITEMNKEYFLD

NONINVENTORYRESALEITEMIMAGE:
  ITEM

NONINVENTORYRESALEITEMITEMACCOUNTINGBOOKDETAIL:
  ITEM

NONINVENTORYRESALEITEMITEMQUANTITYPRICINGLEVEL:
  ITEM

NONINVENTORYRESALEITEMITEMVENDOR:
  PURCHASEPRICE

NONINVENTORYRESALEITEMPRICE:
  DISCOUNT, DISCOUNTDISPLAY, ISINACTIVE, ISONLINE, PRICELEVEL, PRICELEVELNAME, CURRENCYPAGE

NONINVENTORYRESALEITEMQUANTITY:
  ITEM, ID, SEQNUM, MAXCOUNT, MINCOUNT

NONINVENTORYRESALEITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

NONINVENTORYSALEITEMCORRELATEDITEM:
  ITEMNKEYFLD

NONINVENTORYSALEITEMIMAGE:
  ITEM

NONINVENTORYSALEITEMITEMACCOUNTINGBOOKDETAIL:
  ITEM

NONINVENTORYSALEITEMITEMQUANTITYPRICINGLEVEL:
  ITEM

NONINVENTORYSALEITEMPRICE:
  DISCOUNT, DISCOUNTDISPLAY, ISINACTIVE, ISONLINE, PRICELEVEL, PRICELEVELNAME, CURRENCYPAGE

NONINVENTORYSALEITEMQUANTITY:
  ITEM, ID, SEQNUM, MAXCOUNT, MINCOUNT

NONINVENTORYSALEITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

NOTE:
  ENTITY, ACTIVITY, ITEM, EXTERNALID, ID, TRANSACTION

NOTEDIRECTIONTYPE:
  NAME

NOTETYPE:
  NAME, DESCRIPTION, EXTERNALID, ID

OPPORTUNITYBILLINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

OPPORTUNITYSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

ORDERALLOCATIONSTRATEGY:
  ALLOCATEFIRMINVTONLY, FUTUREINVENTORY, ISINACTIVE, NAME, ID

ORDERLINE:
  ITEM

ORDERRELEASELINE:
  CUSTOMERNAME, TRANLINEUNITNAME

ORDERRESERVATION:
  TRANSACTIONDATE, NAME, TRANID, EXTERNALID, ID, ENDDATE, ITEM, CLOSED, LOCATION, COMMITMENTFIRM, ORDERALLOCATIONSTRATEGY, ORDERPRIORITY, UNITS

ORDERSANDRETURNSPROMOTIONCOMBINATIONSMAP:
  TRANSACTIONLINE

ORIGINATINGLEAD:
  ALTEMAIL, ALTPHONE, COMPANYNAME, EMAIL, FAX, FIRSTNAME, HOMEPHONE, LASTNAME, MIDDLENAME, MOBILEPHONE, PHONE

OTHERCHARGEITEMITEMACCOUNTINGBOOKDETAIL:
  ITEM

OTHERCHARGEITEMITEMQUANTITYPRICINGLEVEL:
  ITEM

OTHERCHARGEITEMITEMVENDOR:
  PURCHASEPRICE

OTHERCHARGEITEMPRICE:
  DISCOUNT, DISCOUNTDISPLAY, ISINACTIVE, ISONLINE, PRICELEVEL, PRICELEVELNAME, CURRENCYPAGE

OTHERCHARGEITEMQUANTITY:
  ITEM, ID, SEQNUM, MAXCOUNT, MINCOUNT

OTHERCHARGEITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

OTHERCHARGEPURCHASEITEMITEMACCOUNTINGBOOKDETAIL:
  ITEM

OTHERCHARGEPURCHASEITEMITEMVENDOR:
  PURCHASEPRICE

OTHERCHARGEPURCHASEITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

OTHERCHARGERESALEITEMITEMACCOUNTINGBOOKDETAIL:
  ITEM

OTHERCHARGERESALEITEMITEMQUANTITYPRICINGLEVEL:
  ITEM

OTHERCHARGERESALEITEMITEMVENDOR:
  PURCHASEPRICE

OTHERCHARGERESALEITEMPRICE:
  DISCOUNT, DISCOUNTDISPLAY, ISINACTIVE, ISONLINE, PRICELEVEL, PRICELEVELNAME, CURRENCYPAGE

OTHERCHARGERESALEITEMQUANTITY:
  ITEM, ID, SEQNUM, MAXCOUNT, MINCOUNT

OTHERCHARGERESALEITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

OTHERCHARGESALEITEMITEMACCOUNTINGBOOKDETAIL:
  ITEM

OTHERCHARGESALEITEMITEMQUANTITYPRICINGLEVEL:
  ITEM

OTHERCHARGESALEITEMPRICE:
  DISCOUNT, DISCOUNTDISPLAY, ISINACTIVE, ISONLINE, PRICELEVEL, PRICELEVELNAME, CURRENCYPAGE

OTHERCHARGESALEITEMQUANTITY:
  ITEM, ID, SEQNUM, MAXCOUNT, MINCOUNT

OTHERCHARGESALEITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

OTHERNAME:
  LASTMODIFIEDDATE, NAMEORIG, COMPANYNAME, ENTITYTITLE

OTHERNAMEADDRESSBOOK:
  INTERNALID, ADDRESSBOOKADDRESS, ADDRESSBOOKADDRESS_KEY, ENTITY, DEFAULTBILLING, DEFAULTSHIPPING, LABEL

OTHERNAMEADDRESSBOOKENTITYADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

OTHERNAMEBULKMERGE:
  STATUS

OTHERNAMECAMPAIGNS:
  CAMPAIGNEVENT, DATESENT, CAMPAIGNTEMPLATEID, CAMPAIGNRESPONSEID, RESPONSE, CONTACT, ENTITY, CATEGORY, TITLE

OTHERNAMESUBSCRIPTIONS:
  LASTMODIFIEDDATE

OVERHEADTYPE:
  NAME

PARTNER:
  LASTMODIFIEDDATE, WASINACTIVE, NAMEORIG, DEFAULTADDRESS, ALTEMAIL, PARTNERCODE, COMMENTS, COMPANYNAME, DATECREATED, EMAIL, FAX, HOMEPHONE, ISPERSON, ISINACTIVE, GIVEACCESS, MOBILEPHONE, PHONE, DEFAULTTAXREG, URL

PARTNERADDRESSBOOK:
  INTERNALID, ADDRESSBOOKADDRESS, ADDRESSBOOKADDRESS_KEY, ENTITY, DEFAULTBILLING, DEFAULTSHIPPING, LABEL

PARTNERADDRESSBOOKENTITYADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

PARTNERBULKMERGE:
  STATUS

PARTNERCAMPAIGNS:
  CAMPAIGNEVENT, DATESENT, CAMPAIGNTEMPLATEID, CAMPAIGNRESPONSEID, RESPONSE, CONTACT, ENTITY, CATEGORY, TITLE

PARTNERCATEGORY:
  NAME, PARENT, EXTERNALID, ID

PARTNERCATEGORYMAP:
  PARTNER, CATEGORY

PARTNERCONTACTROLE:
  ROLE, CONTACTNAME

PARTNERSUBSCRIPTIONS:
  LASTMODIFIEDDATE

PAYCHECK:
  TRANDATE

PAYCHECKPAYTIME:
  CUSTJOB, DDATE, SERVICEITEM

PAYCHECKSUMMARY:
  PAYITEMTYPE, PAYITEM, YTDAMOUNT

PAYITEMTYPE:
  NAME, KEY

PAYMENTITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

PAYMENTMETHOD:
  METHODTYPE, LASTMODIFIEDDATE, ACCOUNT, NAME, EXTERNALID, ID

PAYROLLITEM:
  DERIVERATEFROMPAYROLLITEM, DERIVEDRATEMULTIPLIER, EXPENSEACCOUNT, LIABILITYACCOUNT, LIMIT, NAME, ID, ITEMTYPE, VENDOR

PERCENTCOMPLETEOVERRIDE:
  PERIOD, COMMENTS, PERCENT

PERIODFISCALCALENDARS:
  FISCALCALENDAR, PARENT

PERMISSIONLEVEL:
  KEY, NAME

PHONECALL:
  STARTDATE, EXTERNALID, ID, SUPPORTCASE, COMPANY, CONTACT, COMPLETEDDATE, CREATEDDATE, LASTMODIFIEDDATE, MESSAGE, USERNOTES, TRANSACTION, ASSIGNED, OWNER, PHONE, STATUS, TITLE

PHONECALLCOMPANYMAP:
  COMPANY

PICKACTION:
  SHIPADDRESS

PICKTASK:
  SUBSIDIARY

PLANNEDEXPENSEVERSION:
  PLANNEDPERIOD, AMOUNT, PERIODCOMMENTS, DEFERRALACCOUNT, RECOGNITIONACCOUNT, CREATEDBY, DATECHANGED, VERSION

PLANNEDORDER:
  TRANSACTIONCREATED

PLANNEDREVENUETYPE:
  NAME

PLANNEDREVENUEVERSION:
  PLANNEDPERIOD, AMOUNT, PERIODCOMMENTS, DEFERRALACCOUNT, RECOGNITIONACCOUNT, CREATEDBY, DATECHANGED, VERSION

PLANNEDSTANDARDCOST:
  SUBSIDIARY, LASTMODIFIEDDATE, ITEM, MEMO, ID, STANDARDCOSTVERSION

PLANNEDSTANDARDCOSTCOMPONENTS:
  COMPONENTITEM, PLANNEDSTANDARDCOST, COST

POSTINGACCOUNTACTIVITY:
  FAKEID, ACCOUNTINGBOOK, ACCOUNTINGPERIOD, ACTIVITYDATE, AMOUNT, CLASS, CUSTOMTYPE, DEPARTMENT, ENTITY, ITEM, LOCATION, PARTNER, PROMOCODE, QUANTITY, TRANSACTIONTYPE

PRESCATEGORYSITEAUDIENCE:
  SITECATEGORY

PREVIOUSTRANSACTIONLINELINK:
  INVENTORY_NUMBER, PREVIOUSLINE

PREVIOUSTRANSACTIONLINK:
  PREVIOUSDOC

PRICEBOOK:
  NAME, SUBSCRIPTIONPLAN, EXTERNALID, ID

PRICEBOOKLINEINTERVAL:
  FREQUENCY, DISCOUNT, OVERAGEFREQUENCY, OVERAGEDISCOUNT, OVERAGEPRICEPLAN, OVERAGEREPEATEVERY, SUBSCRIPTIONPLANLINE, LINENUMBER, PRICEBOOK, PRICEPLAN, REPEATEVERY, MULTIPLIERLINE, ISREQUIRED, ITEM

PRICELEVEL:
  LASTMODIFIEDDATE, DISCOUNTPCT, ISONLINE, EXTERNALID, ID, NAME

PRICEPLAN:
  INCLUDEDQUANTITY, EXTERNALID, ID

PRICETIERS:
  FROMVAL, MAXAMOUNT, MINAMOUNT, PRICEPLAN, ID, LINEID, VALUE

PRICING:
  CURRENCY, INTERNALID, SALEUNIT

PRICINGGROUP:
  ID

PRICINGWITHCUSTOMERS:
  CURRENCY, INTERNALID, SALEUNIT

PROJECTBILLINGBUDGET:
  AMOUNT, CALCULATED, JOB

PROJECTCOSTBUDGET:
  AMOUNT, CALCULATED, JOB, CALCULATEDFROMALLOCATIONS

PROJECTEXPENSETYPE:
  ACCOUNT, DESCRIPTION, ID

PROJECTRESOURCEAGGREGATE:
  EXTERNALID, ISINACTIVE, LABORCOST, ENTITYID, SUBSIDIARY, ID

PROJECTREVENUERLCHARGERL:
  ACTUALAMOUNT, CHARGERULE, PROJECTREVENUERULE

PROJECTREVENUERULE:
  DESCRIPTION, ISINACTIVE, REVENUERECONCILED, PROJECT, EXTERNALID, ID, NAME, SERVICEITEM

PROJECTREVENUERULEPROJECTREVENUERLCHARGERL:
  ACTUALAMOUNT, CHARGERULE, PROJECTREVENUERULE

PROJECTTASK:
  PERCENTTIMECOMPLETE, PERCENTCOMPLETEBYRSRCALLOC, LASTMODIFIEDDATE, ISINACTIVE, MESSAGE, OWNER, CONTACT

PROJECTTASKASSIGNEE:
  BILLINGCLASS, CALCULATEDWORK, ESTIMATEDWORK, SERVICEITEM, PLANNEDWORK, PROJECTTASK, RESOURCE, UNITCOST, UNITPRICE

PROJECTTASKBILLINGBUDGET:
  AMOUNT, JOBTASK

PROJECTTASKCOSTBUDGET:
  AMOUNT, JOBTASK

PROJECTTASKPREDECESSOR:
  TYPE, LAGDAYS, SUCCESSOR

PROJECTTEMPLATE:
  ALLOWTASKTIMEFORRSRCALLOC, USEALLOCATEDTIMEFORFORECAST, FORECASTCHARGERUNONDEMAND, SOURCESERVICEITEMFROMRATECARD, SCHEDULINGMETHOD, EXTERNALID, ISINACTIVE, ENTITYID, BILLINGRATECARD, SCHEDULEDENDDATE, STARTDATE, LIMITTIMETOASSIGNEES, PROJECTEXPENSETYPE, CBUDGETLABORBUDGETFROMALLOC, BBUDGETUSECALCULATEDVALUES, CBUDGETUSECALCULATEDVALUES

PROJECTTEMPLATEJOBRESOURCEROLEMAP:
  ROLE

PROJECTTIMEAPPROVALTYPE:
  NAME, ID

PROMOTIONCODE:
  APPLYDISCOUNTTO, CODE, CODEPATTERN, LASTMODIFIEDDATE, DESCRIPTION, DISCOUNT, DISPLAYLINEDISCOUNTS, ENDDATE, NAME, IMPLEMENTATION, ID, USETYPE

PROMOTIONCODECAMPAIGNS:
  CAMPAIGN, PROMOTIONCODE

PROMOTIONCODECOUPONINSTANCES:
  CODE, DATESENT, PROMOTIONCODE, RECIPIENT

PROMOTIONCODEDISCOUNTEDITEMS:
  DISCOUNTEDITEM

PROMOTIONCODEITEMS:
  ITEM

PUBLISHEDSAVEDSEARCHAUDIENCE:
  SITECATEGORY

PURCHASEORDERBILLINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

PURCHASEORDEREXPENSEMACHINE:
  EXPENSEITEM

PURCHASEORDERSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

PURCHASEREQUISITIONEXPENSEMACHINE:
  EXPENSEITEM

QUANTITYPRICINGSCHEDULE:
  UNITSTYPE

QUOTA:
  MAMOUNT, ACLASS, DATE, DEPARTMENT, ENTITY, ASA, ITEM, LOCATION, MAMOUNTQUARTERLY, SUBSIDIARY, ISMANAGER

RATABLEEVENTTYPE:
  NAME

REFORECASTMETHOD:
  NAME

RESOURCEALLOCATION:
  ALLOCATIONUNIT, LASTMODIFIEDDATE, ENDDATE, NOTES, NUMBERHOURS, PERCENTOFTIME, PROJECT, PROJECTTASK, REQUESTEDBY, EXTERNALID, ID, ALLOCATIONRESOURCE, STARTDATE, ENTITYNAME

RESOURCEGROUP:
  NAME, DESCRIPTION, ID

RESOURCEGROUPMEMBERS:
  RESOURCE, GROUP

RETURNAUTHORIZATIONBILLINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

RETURNAUTHORIZATIONSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

RETURNAUTHORIZATIONTRANPROMOTION:
  DISCOUNTISTAXABLE

REVENUEALLOCATIONGROUP:
  NAME

REVENUECOMMITMENTBILLINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

REVENUECOMMITMENTREVERSALBILLINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

REVENUECOMMITMENTREVERSALSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

REVENUECOMMITMENTSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

REVENUEELEMENT:
  DEFERCONTRACTEXPENSEACCT, JOURNALENTRY, REVENUEARRANGEMENT, ALTERNATEUNITSTYPE, CONTINGENTREVENUEHANDLING, DELIVERED, ACCOUNTINGBOOK, CATCHUPPERIOD, ALLOCATEDCONTRACTCOSTAMOUNT, ALLOCATIONAMOUNT, ALTERNATEQUANTITY, ALTERNATEUNITS, AMORTIZATIONSCHEDULE, AMORTIZATIONSTARTDATE, AMORTIZATIONTEMPLATE, CALCULATEDAMOUNT, CARVEINAMOUNT, CARVEINRATIO, CARVEOUTAMOUNT, CARVEOUTRATIO, ...

REVENUEELEMENTSOURCETYPE:
  NAME

REVENUEPLAN:
  CATCHUPPERIOD, COMMENTS, LASTMODIFIEDDATE, REVRECENDDATE, REVENUERECOGNITIONRULE, HOLDREVENUERECOGNITION, ID, RECORDNUMBER, REVRECSTARTDATE, ACCOUNTINGBOOK, ITEM, CREATEDFROM

REVENUEPLANPLANNEDCOST:
  DATEEXECUTED

REVENUEPLANPLANNEDREVENUE:
  DATEEXECUTED

REVENUEPLANSTATUS:
  NAME

REVENUEPLANTYPE:
  NAME

REVENUERECOGNITIONRULE:
  ID, NAME, PERIODOFFSET, RECOGNITIONPERIOD, STARTOFFSET, TERMINDAYS, TERMINMONTHS, CREATEDDATE, LASTMODIFIEDDATE

REVRECAMOUNTSOURCETYPE:
  NAME

REVRECCHANGEIMPACTTYPE:
  NAME

REVRECDATESOURCETYPE:
  NAME

REVRECEVENTPREVRULE:
  KEY, NAME

REVRECEVENTTRANLINE:
  KEY

REVRECRECURRENCETYPE:
  NAME

REVRECSCHEDULE:
  TOTALAMOUNT, INITIALAMOUNT, ISSCHEDULE, NAME, PERIODOFFSET, ID, RECURRENCETYPE, SCHEDULENUMBER, AMORTIZATIONTYPE, REVRECOFFSET, RECOGINTERVALSRC, ACCOUNTINGBOOK, ENDDATE, STARTDATE

REVRECSCHEDULERECURRENCE:
  POSTINGPERIOD, ISRECOGNIZED, REVRECSCHEDULE, JDATE, JOURNAL_ID, INCOMEACCOUNT, RECAMOUNT, JOURNAL

REVRECTEMPLATERECURRENCE:
  REVRECTEMPLATE, INCOMEACCOUNT

ROUNDINGGAINLOSS:
  ACCOUNT, BASEAMOUNT, CURRENCY, ENTITY, FOREIGNCURRENCYBALANCE, ISTAXREGISTRATIONOVERRIDE, ACCOUNTLEGALNAME, ROUNDINGGAINORLOSS, PROMOTIONID, CLASSIFICATION, DEPARTMENT, TRANSACTIONLINENUMBER, LOCATION, MEMO, TRANSACTIONNUMBER, POSTINGPERIOD, SUBSIDIARY, SOURCETRANSACTIONDATE, TRANSACTIONEXCHANGERATE, SOURCETRANSACTIONNUMBER, ...

SALESCHANNEL:
  DESCRIPTION, ISINACTIVE, NAME, ORDERPRIORITY, ID, ONLYUSERESERVATIONASSUPPLY

SALESINVOICEDPROMOTIONCOMBINATIONSMAP:
  TRANSACTIONLINE

SALESORDERBILLINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

SALESORDEREDPROMOTIONCOMBINATIONSMAP:
  TRANSACTIONLINE

SALESORDERGIFTCERTREDEMPTION:
  AUTHCODE

SALESORDERITEMSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

SALESORDERSHIPGROUP:
  HANDLINGLINEID, DOC

SALESORDERSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

SALESORDERTRANPROMOTION:
  DISCOUNTISTAXABLE

SALESOVERVIEWSALESINVOICEDPROMOTIONCOMBINATIONSMAP:
  TRANSACTIONLINE

SALESROLE:
  DESCRIPTION, ISINACTIVE, ISSALESREP, NAME, EXTERNALID, ID

SALESTAXITEM:
  PURCHASEACCOUNT, FULLNAME, INCLUDECHILDREN, SALEACCOUNT, TAXACCOUNT, EXEMPT, ID, NAME, PARENT, TAXAGENCY, LASTMODIFIEDDATE, ITEMID, RATE, CITY, COUNTY, STATE, TAXTYPE, ZIP

SALESTERRITORY:
  LASTMODIFIEDDATE, DESCR, INACTIVE, NAME, PRIORITY, ID

SALESTERRITORY, ESCALATIONTERRITORY, SUPPORTTERRITORY:
  LASTMODIFIEDDATE, DESCR, INACTIVE, NAME, ID

SALESTERRITORY, ESCALATIONTERRITORYENTITY, SUPPORTTERRITORYENTITY:
  ENTITY, TERRITORY

SALESTERRITORYENTITY:
  TERRITORY

SCRIPTCUSTOMRECORDTYPE:
  NAME

SEARCHCAMPAIGN:
  ISINACTIVE, MESSAGE, OWNER, STARTDATE, TITLE

SEARCHCAMPAIGNITEM:
  CAMPAIGN, ITEM

SERVICEITEMBILLINGRATE:
  BILLINGCLASS, CURRENCYPAGE, ITEM, RATE

SERVICEITEMCORRELATEDITEM:
  ITEMNKEYFLD

SERVICEITEMIMAGE:
  ITEM

SERVICEITEMITEMACCOUNTINGBOOKDETAIL:
  ITEM

SERVICEITEMITEMQUANTITYPRICINGLEVEL:
  ITEM

SERVICEITEMITEMVENDOR:
  PURCHASEPRICE

SERVICEITEMPRICE:
  DISCOUNT, DISCOUNTDISPLAY, ISINACTIVE, ISONLINE, PRICELEVEL, PRICELEVELNAME, CURRENCYPAGE

SERVICEITEMQUANTITY:
  ITEM, ID, SEQNUM, MAXCOUNT, MINCOUNT

SERVICEITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

SERVICEPURCHASEITEMITEMACCOUNTINGBOOKDETAIL:
  ITEM

SERVICEPURCHASEITEMITEMVENDOR:
  PURCHASEPRICE

SERVICEPURCHASEITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

SERVICERESALEITEMBILLINGRATE:
  BILLINGCLASS, CURRENCYPAGE, ITEM, RATE

SERVICERESALEITEMCORRELATEDITEM:
  ITEMNKEYFLD

SERVICERESALEITEMIMAGE:
  ITEM

SERVICERESALEITEMITEMACCOUNTINGBOOKDETAIL:
  ITEM

SERVICERESALEITEMITEMQUANTITYPRICINGLEVEL:
  ITEM

SERVICERESALEITEMITEMVENDOR:
  PURCHASEPRICE

SERVICERESALEITEMPRICE:
  DISCOUNT, DISCOUNTDISPLAY, ISINACTIVE, ISONLINE, PRICELEVEL, PRICELEVELNAME, CURRENCYPAGE

SERVICERESALEITEMQUANTITY:
  ITEM, ID, SEQNUM, MAXCOUNT, MINCOUNT

SERVICERESALEITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

SERVICESALEITEMBILLINGRATE:
  BILLINGCLASS, CURRENCYPAGE, ITEM, RATE

SERVICESALEITEMCORRELATEDITEM:
  ITEMNKEYFLD

SERVICESALEITEMIMAGE:
  ITEM

SERVICESALEITEMITEMACCOUNTINGBOOKDETAIL:
  ITEM

SERVICESALEITEMITEMQUANTITYPRICINGLEVEL:
  ITEM

SERVICESALEITEMPRICE:
  DISCOUNT, DISCOUNTDISPLAY, ISINACTIVE, ISONLINE, PRICELEVEL, PRICELEVELNAME, CURRENCYPAGE

SERVICESALEITEMQUANTITY:
  ITEM, ID, SEQNUM, MAXCOUNT, MINCOUNT

SERVICESALEITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

SHIPGROUP:
  HANDLINGLINEID, DOC, SHIPPINGMETHOD

SHIPITEM:
  SUBSIDIARY, FEDEXONERATE, ISTAXABLE

SHIPITEMFREESHIPPINGITEM:
  ITEM

SHIPMENTPACKAGE:
  ALCOHOLRECIPIENTTYPE, AUTHORIZATIONNUMBER, CASHONDELIVERYAMOUNT, CODOTHERCHARGE, CONTENTSDESCRIPTION, DECLAREDVALUE, INSUREDVALUE, DIMENSIONUNIT, DRYICEWEIGHT, FREIGHTCHARGEADDEDTOCOD, HASADDITIONALHANDLING, HASCASHONDELIVERY, HASDECLAREDVALUE, HASINSUREDVALUE, ISALCOHOL, ISNONHAZARDOUSLIBATTERIES, ISNONSTANDARDCONTAINER, ITEMFULFILLMENT, HEIGHT, LENGTH, ...

SHIPPERPACKAGETYPECODE:
  NAME

SHIPPINGMETHODRULERELATION:
  SUBSIDIARY

SHIPPINGPACKAGE:
  PKGNAME

SOLUITON:
  DISPLAYONLINE

SOLUTION:
  MESSAGE, EXTERNALID, ASSIGNED, LASTMODIFIEDDATE, SOLUTIONCODE, LONGDESCRIPTION, ID, TITLE

SOLUTIONTOPICMAP:
  SOLUTION, TOPIC

SOURCEDETAILS:
  REVENUEELEMENT, SOURCEID, SOURCETYPE

STATE:
  SHORTNAME, ID

STATISTICALJOURNALENTRY:
  UNITSTYPE

STATISTICALJOURNALENTRYLINE:
  JOURNAL, RITEMCOUNT, MEMO, LINE, KPAYITEM, ENTITY2, REVENUERECOGNITIONRULE, LINEUNIQUEKEY, LINEUNIT, CONVERSIONRATE

STOREPICKUPFULFILLMENT:
  POSTINGPERIOD, CREATEDDATE, LASTMODIFIEDDATE, TRANDATE, EXTERNALID, ID, PARTNER, PICKEDUPDATE

STOREPICKUPFULFILLMENTITEM:
  SRCDOC, STOREPICKUPFULFILLMENT, UNITS, ITEMKEY, ITEMNAME, ITEMNAME_SELECTOR, SITEMNAME, COUNTRYOFMANUFACTURE, ISHAZMATITEM, HAZMATHAZARDCLASS, HAZMATID, HAZMATITEMUNITS, HAZMATITEMUNITSQTY, HAZMATPACKINGGROUP, HAZMATSHIPPINGNAME, ONHAND, ITEMSUBTYPE, ITEMUPC, ITEMWEIGHT, AMOUNT, ...

SUBSCRIPTION:
  BILLINGSCHEDULE, LASTBILLDATE, LASTBILLCYCLEDATE, NEXTBILLCYCLEDATE, FREQUENCY, PRICEINTERVAL.DISCOUNTPERCENT, PRICEINTERVAL.DISCOUNTAMOUNT, ADVANCERENEWALPERIODNUMBER, BILLINGACCOUNT, CLASS, CUSTOMER, CREATEDDATE, ENDDATE, ESTIMATEDREVRECENDDATE, STARTDATE, DEFAULTRENEWALMETHOD, DEFAULTRENEWALPLAN, DEFAULTRENEWALPRICEBOOK, DEFAULTRENEWALTERM, DEFAULTRENEWALTRANTYPE, ...

SUBSCRIPTION.PRICEINTERVAL:
  ID

SUBSCRIPTIONCHANGEORDER:
  BILLINGACCOUNT, CUSTOMER, SUBSCRIPTIONENDDATE, SUBSCRIPTIONSTARTDATE, SUBSCRIPTIONRENEWALPLAN, SUBSCRIPTIONRENEWALTRANTYPE, SUBSCRIPTIONNAME, SUBSCRIPTIONPLAN, SUBSCRIPTIONNUMBER, SUBSIDIARY, RENEWALPLANNAME, SUBSCRIPTIONTERMDURATION, SUBSCRIPTIONTERMTYPE, SUBSCRIPTIONTERMUNITS

SUBSCRIPTIONCHANGEORDERLINE:
  ITEMDISPLAY

SUBSCRIPTIONCHANGEORDERNEWLINE:
  SUBSCRIPTIONLINE, ITEMDISPLAY, DISCOUNT, PLANITEM, SEQUENCE, PRICEPLAN, MULTIPLIERLINE, ITEM

SUBSCRIPTIONCHANGEORDERRENEWALSTEPS:
  SUBSCRIPTIONDISPLAY

SUBSCRIPTIONLINE:
  CURRENCY, BILLINGACCOUNTSTARTDATE, BILLINGMODE, CATALOGTYPE, CLASS, CREATEDDATE, ENDDATE, PREVENDDATE, LASTMODIFIEDDATE, RECURRENCESTARTDATE, PREVSTARTDATE, STARTDATE, TERMINATIONDATE, DEPARTMENT, SUBLINEDISCOUNT, INCLUDEINRENEWAL, INCLUDEINRENEWALORIG, PRORATEENDDATE, PRORATESTARTDATE, ITEM, ...

SUBSCRIPTIONLINEREVISION:
  CHANGEORDER, CHANGEORDEREFFECTIVEDATE, DATECREATED, DATEEND, DELTAAMOUNT, DELTAQUANTITY, SUBSCRIPTIONLINEDISCOUNT, APPLIEDTOCHANGEORDER, CREATEDFROMVOID, OVERAGEDISCOUNT, OVERAGEPRICEPLAN, PRICEPLAN, QUANTITY, RECURRINGAMOUNT, REVENUEELEMENT, SUBSCRIPTIONLINE, SUBSCRIPTIONREVISION, TOTALCONTRACTVALUE

SUBSCRIPTIONMIDTERMUPLIFT:
  SUBSCRIPTION

SUBSCRIPTIONPLAN:
  ADVANCERENEWALPERIODUNIT, DEFAULTRENEWALMETHOD, DEFAULTRENEWALPLAN, DEFAULTRENEWALTERM, DEFAULTRENEWALTRANTYPE, INITIALTERM, AUTORENEWAL

SUBSCRIPTIONPLANMEMBER:
  ID, LINEID, LINENUMBER, BILLINGMODE, PRORATEENDDATE, PRORATESTARTDATE, ISREQUIRED, ITEM, SUBSCRIPTIONPLAN, RENEWALOPTION

SUBSCRIPTIONPLANMIDTERMUPLIFT:
  SUBSCRIPTIONPLAN

SUBSCRIPTIONPLANRENEWALUPLIFT:
  LINEID, LINENUMBER, ITEM

SUBSCRIPTIONPLANSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

SUBSCRIPTIONPRICEINTERVAL:
  CATALOGTYPE, SUBSCRIPTION, SUBSCRIPTIONPLANLINE, ITEM

SUBSCRIPTIONTERM:
  SUBSCRIPTIONTERMDURATION, EXTERNALID, ID, SUBSCRIPTIONTERMTYPE, SUBSCRIPTIONTERMUNIT

SUBSIDIARYACCOUNTINGBOOKDETAIL:
  CURRENCY, SUBSIDIARY

SUBSIDIARYMAINADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

SUBSIDIARYRETURNADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

SUBSIDIARYSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

SUBTOTALITEMSUBSIDIARYMAP:
  ITEM, SUBSIDIARY

SUITESCRIPTDETAIL:
  ENTITY, ROLE

SUPPLYCHAINSNAPSHOTDETAILS:
  TRANTYPE

SUPPLYCHANGEORDER:
  TRANSACTION, ITEM

SUPPLYREPLENISHMENTTYPE:
  NAME

SUPPORTCASE:
  SUBSIDIARY, LASTMESSAGEDATE, LASTMODIFIEDDATE, EXTERNALID, ASSIGNED, STARTDATE, EMAIL, ID, ISSUE, CASENUMBER, ORIGIN, PHONE, PROFILE, CATEGORY, COMPANY, COMPANYRESTRICTION, DATECREATED, ENDDATE, HELPDESK, INBOUNDEMAIL, ...

SUPPORTCASEESCALATEHIST:
  SUPPORTCASE, TOENTITY, DATETIME, FROMENTITY, MESSAGE

SUPPORTCASEORIGIN:
  EXTERNALID, ID

SUPPORTCASESOLUTIONMAP:
  SOLUTION, SUPPORTCASE

SUPPORTCASETYPE:
  EXTERNALID, ID

SYSTEMNOTE:
  NAME, RECORDID, CONTEXT, FIELD, DATE, LINEID, LINETRANSACTIONID, TYPE, RECORDTYPEID, ROLE, NEWVALUE, OLDVALUE, CUSTOMFIELD.OWNER, CUSTOMFIELD.LASTMODIFIEDDATE

TASK:
  STARTDATE, COMPANY, CONTACT, MESSAGE, TRANSACTION, ASSIGNED, TITLE, CREATEDDATE, LASTMODIFIEDDATE, DUEDATE, ESTIMATEDTIME, ESTIMATEDTIMEOVERRIDE, OWNER, PRIORITY, STATUS, EXTERNALID, ID, ORDER

TASKCOMPANYMAP:
  COMPANY

TASKCONTACTMAP:
  CONTACT, TASK

TASKSFIXEDAMOUNT:
  FIXEDAMOUNT, ROWKEY, PROJECTREVENUERULE, PROJECTTASK

TASKSPCTFROMTOTAL:
  PERCENTFROMTOTAL, ROWKEY, PROJECTREVENUERULE, PROJECTTASK

TAXITEMTAXGROUP:
  FULLNAME, INCLUDECHILDREN, ID, ITEMID, RATE, CITY, COUNTY, STATE, TAXTYPE, ZIP

TAXPERIODFISCALCALENDARS:
  FISCALCALENDAR, PARENT

TERM:
  DATEDRIVEN, LASTMODIFIEDDATE, RECURRENCEFREQUENCY, RECURRENCECOUNT, INSTALLMENT, PAYTAXUPFRONT, PREFERRED, SPLITEVENLY, DUENEXTMONTHIFWITHINDAYS, NAME, TERM, EXTERNALID, ID, REPEATEVERY

TESTCELL:
  GROUP, CELLNAME, CELLPERCENT, CELLID

TIMEBILL:
  SUPERVISORAPPROVAL, ISBILLABLE, BILLINGCLASS, BILLINGSUBSIDIARY, CLASS, CLOSED, MEMO, CUSTOMER, TRANDATE, DEPARTMENT, HOURS, EMPLOYEE, VENDOR, ID, HOURSEND, ACTIVITY, CASETASKEVENT, OUTSIDEPROJECTPLAN, POSTED, ISPRODUCTIVE, ...

TIMELINEAPPROVALSTATUS:
  NAME

TIMESHEET:
  EMPLOYEE, ENDDATE, STARTDATE, TRANDATE

TOPIC:
  DESCRIPTION, ISINACTIVE, LONGDESCRIPTION, TITLE, PARENTTTOPIC, EXTERNALID, ID

TOPICPUBLISH:
  ID

TRACKINGNUMBER:
  ID, TRACKINGNUMBER

TRANPROMOTION:
  DISCOUNTISTAXABLE

TRANSACTION CONTACT:
  CONTACT, CONTACTROLE, LASTMODIFIEDDATE, TRANSACTION

TRANSACTION LINE:
  ACCOUNTINGIMPACT.ACCOUNT, ACCOUNTINGIMPACT.AMOUNT, FOREIGNAMOUNT, CLASS, ENTITY, DEPARTMENT, QUANTITY, ITEM, ISCLOSED, RATE, LANDEDCOSTSOURCELINEID, LOCATION, MEMO, ACCOUNTINGIMPACT.NETAMOUNT, QUANTITYSHIPRECV, SUBSIDIARY, TRANSACTION, ID, LINESEQUENCENUMBER, UNITCOSTOVERRIDE

TRANSACTIONACCOUNTINGLINE:
  OVERHEADPARENTITEM, SUBSIDIARYBOOKCURRENCY, CATCHUPPERIOD, REVRECENDDATE, REVRECSTARTDATE, GLAUDITNUMBER, GLAUDITNUMBERSEQUENCE, DEFERREVREC, REVRECSCHEDULE, TRANSACTION, TRANSACTIONLINE, REVENUECOMMITTEDDATE

TRANSACTIONADDRESSBOOK:
  INTERNALID, DEFAULTBILLING, DEFAULTSHIPPING, LABEL

TRANSACTIONADDRESSMAPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

TRANSACTIONBILLING:
  BILLAMOUNT, BILLAMOUNTFOREIGN, BILLCOUNT, BILLDATE, BILLNETAMOUNT, BILLNETAMOUNTFOREIGN, PAYMENTTERMS, REVRECENDDATE, REVRECSTARTDATE, TRANSACTION, TRANSACTIONLINE

TRANSACTIONBILLINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

TRANSACTIONBILLINGADDRESSBOOK:
  INTERNALID, ADDRESSBOOKADDRESS, ADDRESSBOOKADDRESS_KEY, DEFAULTBILLING, DEFAULTSHIPPING, LABEL

TRANSACTIONBILLINGADDRESSBOOKENTITYADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

TRANSACTIONHISTORY:
  ACTION, AMOUNT, AMOUNTWITHCURRENCY, DATETIME, TRANSACTIONDATE, DOCUMENTNUMBER, INTERNALID, TRANSACTION, TRANSACTIONNUMBER, TYPE, USERNAME

TRANSACTIONLINEADDRESSMAPPING:
  TRANSACTIONLINE

TRANSACTIONLINEADDRESSMAPPINGLINEADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

TRANSACTIONNOTE:
  EXTERNALID, ID, TRANSACTION

TRANSACTIONNOTE, ITEMNOTE, SUPPORTCASENOTE, ENTITYNOTE:
  AUTHOR, NOTE, LASTMODIFIEDDATE, DIRECTION, TITLE, NOTETYPE, ID, NOTEDATE

TRANSACTIONPARTNER:
  CONTRIBUTION, ISPRIMARY, PARTNER, PARTNERROLE, TRANSACTION

TRANSACTIONPAYEEADDRESSBOOK:
  INTERNALID, ADDRESSBOOKADDRESS, ADDRESSBOOKADDRESS_KEY, DEFAULTBILLING, DEFAULTSHIPPING, LABEL

TRANSACTIONPAYEEADDRESSBOOKENTITYADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

TRANSACTIONRETURNADDRESS:
  ADDR1, ADDR2, CITY, COUNTRY, STATE, ZIP

TRANSACTIONRETURNADDRESSBOOK:
  INTERNALID, ADDRESSBOOKADDRESS, ADDRESSBOOKADDRESS_KEY, DEFAULTBILLING, DEFAULTSHIPPING, LABEL

TRANSACTIONRETURNADDRESSBOOKENTITYADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

TRANSACTIONSALESTEAM:
  CONTRIBUTION, LASTMODIFIEDDATE, ISPRIMARY, EMPLOYEE, SALESROLE, TRANSACTION

TRANSACTIONSHIPMENT:
  TRANSHIPPINGGROUP, DOC

TRANSACTIONSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

TRANSACTIONSHIPPINGADDRESSBOOK:
  INTERNALID, ADDRESSBOOKADDRESS, ADDRESSBOOKADDRESS_KEY, DEFAULTBILLING, DEFAULTSHIPPING, LABEL

TRANSACTIONSHIPPINGADDRESSBOOKENTITYADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

TRANSACTIONTAXDETAIL:
  TAXACCOUNT, BASETAXAMOUNT, TAXAMOUNT, NETAMOUNT, CALCDETAIL, TAXBASIS, TAXCODE, TAXRATE, TAXTYPE, LINE, LINENUMBER

TRANSFERORDERSHIPPINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

UNITSTYPE:
  LASTMODIFIEDDATE, NAME, EXTERNALID, ID

UNITSTYPEUOM:
  INTERNALID, UNITSTYPE, ABBREVIATION, CONVERSIONRATE, BASEUNIT, UNITNAME, PLURALABBREVIATION, PLURALNAME

UNLOCKEDTIMEPERIOD:
  ENDDATE, STARTDATE, VALIDUNTIL, ENTITY, EXTERNALID, ID

UNREALIZEDGAINLOSS:
  ACCOUNT, BASEAMOUNT, ENDINGEXCHANGERATE, CURRENCY, ENTITY, FOREIGNCURRENCYBALANCE, ISTAXREGISTRATIONOVERRIDE, ACCOUNTLEGALNAME, NETGAINORLOSS, PRIORGAINORLOSS, PROMOTIONID, CLASSIFICATION, DEPARTMENT, TRANSACTIONLINENUMBER, LOCATION, MEMO, TRANSACTIONNUMBER, POSTINGPERIOD, REVALUATIONTYPE, SUBSIDIARY, ...

USAGE:
  USAGEDATE, STATUS, CUSTOMER, EXTERNALID, ID, ITEM, MEMO, USAGEQUANTITY, USAGESUBSCRIPTION, USAGESUBSCRIPTIONLINE, SUBSCRIPTIONPLAN

VENDORADDRESSBOOK:
  INTERNALID, ADDRESSBOOKADDRESS, ADDRESSBOOKADDRESS_KEY, ENTITY, DEFAULTBILLING, DEFAULTSHIPPING, LABEL

VENDORADDRESSBOOKENTITYADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

VENDORBILLBILLINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

VENDORBILLEXPENSEMACHINE:
  EXPENSEITEM

VENDORBILLINSTALLMENT:
  CURRENCY

VENDORBULKMERGE:
  STATUS

VENDORCAMPAIGNS:
  CAMPAIGNEVENT, DATESENT, CAMPAIGNTEMPLATEID, CAMPAIGNRESPONSEID, RESPONSE, CONTACT, ENTITY, CATEGORY, TITLE

VENDORCATEGORY:
  ISINACTIVE, NAME, EXTERNALID, ID

VENDORCREDITBILLINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

VENDORCREDITEXPENSEMACHINE:
  EXPENSEITEM

VENDORCURRENCYBALANCE:
  CURRENCY, INTRANSITBALANCE, BALANCE, PREPAYMENTBALANCE, UNBILLEDORDERS, VENDOR

VENDORPAYMENTPAYEEADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

VENDORPREPAYMENTPAYEEADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

VENDORRETURNAUTHORIZATIONBILLINGADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP

VENDORRETURNAUTHORIZATIONEXPENSEMACHINE:
  EXPENSEITEM

VENDORROLES:
  ENTITY, SELECTEDROLE

VENDORROLESFORSEARCH:
  ENTITY, ROLE

VENDORSUBSCRIPTIONS:
  LASTMODIFIEDDATE

VENDORSUBSIDIARYRELATIONSHIP:
  BASECURRENCY, SUBSIDIARY, BALANCE, BALANCEBASE, CREDITLIMIT, UNBILLEDORDERS, UNBILLEDORDERSBASE, ENTITY, EXTERNALID, ID

VENDORTAXREGISTRATION:
  TAXREGISTRATIONNUMBER

VSOESOPGROUPTYPE:
  NAME

WAVEORDERLINE:
  ITEM

WAVEPICKTASK:
  SUBSIDIARY

WAVEWAVEPICKTASK:
  SUBSIDIARY

WINLOSSREASON:
  ISINACTIVE, NAME, EXTERNALID, ID

WORKCALENDAR:
  ISDEFAULT, FRIDAY, MONDAY, SATURDAY, SUNDAY, THURSDAY, TUESDAY, WEDNESDAY, COMMENTS, NAME, STARTHOUR, ID, WORKHOURSPERDAY

WORKCALENDARHOLIDAY:
  EXCEPTIONDATE, DESCRIPTION, WORKCALENDAR

WORKPLACEMAINADDRESS:
  ADDRTEXT, NKEY, RECORDOWNER, ADDR1, ADDR2, ADDR3, ATTENTION, CITY, ADDRESSEE, COUNTRY, LASTMODIFIEDDATE, OVERRIDE, ADDRPHONE, DROPDOWNSTATE, STATE, ZIP
"""