"""
NetSuite SuiteAnalytics Connect (NS2) Schema
Condensed version with most commonly used tables.
Use SQL-92 standard syntax.
"""

NETSUITE_SCHEMA = """
NetSuite SuiteAnalytics Connect (NS2) Database Schema
======================================================
Use SQL-92 standard syntax. Table and column names are case-insensitive.

IMPORTANT SQL-92 RULES:
- Use standard JOINs: INNER JOIN, LEFT JOIN, RIGHT JOIN
- For row limits, wrap query: SELECT * FROM (your_query) WHERE ROWNUM <= N
- Use single quotes for strings: WHERE status = 'Active'
- Use IS NULL / IS NOT NULL for null checks
- Date format: TO_DATE('2024-01-01', 'YYYY-MM-DD')
- Boolean fields use 'T' for true and 'F' for false
- NO semicolons at end of query
- NO FETCH FIRST or LIMIT clause

CORE TABLES:

EMPLOYEE:
  ID, ENTITYID, FIRSTNAME, LASTNAME, MIDDLENAME, EMAIL, PHONE, TITLE,
  HIREDATE, RELEASEDATE, LASTREVIEWDATE, NEXTREVIEWDATE, BIRTHDATE,
  SUPERVISOR, DEPARTMENT, LOCATION, SUBSIDIARY, CLASS,
  ISINACTIVE, GIVEACCESS, DATECREATED, LASTMODIFIEDDATE,
  EMPLOYEETYPE, LABORCOST, EXTERNALID, COMMENTS, SALUTATION

CUSTOMER:
  ID, ENTITYID, COMPANYNAME, FIRSTNAME, LASTNAME, MIDDLENAME,
  EMAIL, PHONE, FAX, ALTPHONE, ALTEMAIL, HOMEPHONE, MOBILEPHONE,
  DATECREATED, LASTMODIFIEDDATE, CATEGORY, SUBSIDIARY, SALESREP,
  CREDITLIMIT, BALANCE, DEPOSITBALANCE, CONSOLBALANCE,
  ISINACTIVE, ISPERSON, TAXABLE, ONCREDITHOLD, ENTITYSTATUS,
  CURRENCY, TERMS, PRICELEVEL, TERRITORY, PARTNER, LEADSOURCE,
  WEBLEAD, EXTERNALID, PARENT, URL, COMMENTS, ACCOUNTNUMBER

VENDOR:
  ID, ENTITYID, COMPANYNAME, FIRSTNAME, LASTNAME, MIDDLENAME,
  EMAIL, PHONE, FAX, ALTPHONE, HOMEPHONE, MOBILEPHONE,
  DATECREATED, LASTMODIFIEDDATE, SUBSIDIARY, CATEGORY,
  CREDITLIMIT, BALANCE, ISINACTIVE, ISPERSON, IS1099ELIGIBLE,
  CURRENCY, TERMS, EXTERNALID, TAXIDNUM, COMMENTS, ACCOUNTNUMBER

TRANSACTION:
  ID, TRANID, TRANDATE, TYPE, STATUS, ENTITY, SUBSIDIARY,
  DEPARTMENT, LOCATION, CLASS, CURRENCY, EXCHANGERATE,
  MEMO, DUEDATE, CLOSEDATE, STARTDATE, ENDDATE, POSTINGPERIOD,
  CREATEDDATE, LASTMODIFIEDDATE, CREATEDBY, EMPLOYEE, PARTNER,
  TERMS, FOB, SHIPMETHOD, EXTERNALID, SOURCE, POSTING, JOB

TRANSACTIONLINE:
  ID, TRANSACTION, LINESEQUENCENUMBER, ITEM, QUANTITY, RATE, AMOUNT,
  ACCOUNT, DEPARTMENT, LOCATION, CLASS, SUBSIDIARY, ENTITY,
  MEMO, ISCLOSED, ISBILLABLE, TAXCODE, TAXLINE, NETAMOUNT, GROSSAMT,
  EXPENSEACCOUNT, CATEGORY, PRICE, UNITS, DUEDATE, UNIQUEKEY

ITEM:
  ID, ITEMID, DISPLAYNAME, FULLNAME, DESCRIPTION, TYPE, ITEMTYPE,
  ISINACTIVE, QUANTITYONHAND, QUANTITYONORDER, VENDOR,
  EXPENSEACCOUNT, EXTERNALID, DATECREATED, LASTMODIFIEDDATE

ACCOUNT:
  ID, ACCTNUMBER, ACCTNAME, ACCTTYPE, BALANCE,
  ISINACTIVE, ISSUMMARY, EXTERNALID, LASTMODIFIEDDATE,
  DEPARTMENT, LOCATION, CLASS

SUBSIDIARY:
  ID, NAME, FULLNAME, ISINACTIVE, ISELIMINATION,
  CURRENCY, COUNTRY, LEGALNAME, FEDERALIDNUMBER, PARENT,
  LASTMODIFIEDDATE, EXTERNALID

DEPARTMENT:
  ID, NAME, ISINACTIVE, PARENT, SUBSIDIARY, EXTERNALID, LASTMODIFIEDDATE

LOCATION:
  ID, NAME, ISINACTIVE, PARENT, SUBSIDIARY, EXTERNALID, LASTMODIFIEDDATE

CLASS (CLASSIFICATION):
  ID, NAME, ISINACTIVE, PARENT, SUBSIDIARY, EXTERNALID

CONTACT:
  ID, ENTITYID, FIRSTNAME, LASTNAME, MIDDLENAME, EMAIL, PHONE,
  COMPANY, TITLE, ISINACTIVE, EXTERNALID, DATECREATED, LASTMODIFIEDDATE

JOB (PROJECT):
  ID, ENTITYID, COMPANYNAME, PARENT, PROJECTMANAGER,
  ISINACTIVE, DATECREATED, LASTMODIFIEDDATE, EXTERNALID

ENTITY (BASE FOR CUSTOMER/VENDOR/EMPLOYEE):
  ID, ENTITYID, FIRSTNAME, LASTNAME, MIDDLENAME, EMAIL, PHONE,
  TYPE, ISINACTIVE, DATECREATED, LASTMODIFIEDDATE, EXTERNALID

ACCOUNTINGPERIOD:
  ID, PERIODNAME, STARTDATE, ENDDATE, CLOSED, ISINACTIVE,
  ISQUARTER, ISYEAR, PARENT, LASTMODIFIEDDATE

CURRENCY:
  ID, NAME, SYMBOL, ISINACTIVE, CURRENCYPRECISION, EXTERNALID

TRANSACTION TYPES (use in WHERE TYPE = 'value'):
  'Sales Order', 'Invoice', 'Cash Sale', 'Credit Memo', 'Customer Payment',
  'Purchase Order', 'Vendor Bill', 'Vendor Credit', 'Vendor Payment',
  'Journal', 'Expense Report', 'Item Fulfillment', 'Item Receipt',
  'Transfer Order', 'Work Order', 'Inventory Adjustment', 'Deposit'

COMMON QUERY PATTERNS:

-- Count employees
SELECT COUNT(*) AS total FROM EMPLOYEE WHERE ISINACTIVE = 'F'

-- List active customers
SELECT * FROM (SELECT ID, COMPANYNAME, EMAIL FROM CUSTOMER WHERE ISINACTIVE = 'F') WHERE ROWNUM <= 50

-- Get transactions by type
SELECT * FROM (SELECT ID, TRANID, TRANDATE, ENTITY FROM TRANSACTION WHERE TYPE = 'Invoice') WHERE ROWNUM <= 50

-- Join transaction with lines
SELECT T.TRANID, T.TRANDATE, TL.ITEM, TL.QUANTITY, TL.AMOUNT
FROM TRANSACTION T
INNER JOIN TRANSACTIONLINE TL ON T.ID = TL.TRANSACTION
WHERE T.TYPE = 'Sales Order'
"""
