"""Drop FK constraint on ns_transactionline.transaction.

Revision ID: 20260205_0001
Revises: 20260202_0004
Create Date: 2026-02-05

The FK constraint causes sync failures because transaction lines may reference
transactions that weren't synced (different date ranges, etc.). Since this is
a mirror of external data, we can't guarantee referential integrity.
"""
from alembic import op


# revision identifiers
revision = "20260205_0001"
down_revision = "20260202_0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Drop the FK constraint if it exists
    # The constraint name is auto-generated by SQLAlchemy
    op.drop_constraint(
        "ns_transactionline_transaction_fkey",
        "ns_transactionline",
        type_="foreignkey"
    )


def downgrade() -> None:
    # Re-add the FK constraint
    op.create_foreign_key(
        "ns_transactionline_transaction_fkey",
        "ns_transactionline",
        "ns_transaction",
        ["transaction"],
        ["id"]
    )
